### ISSUE TITLE
We should mention explicitly that Eclipse plugin has dependency on .NET SDK

### ISSUE THREAD

**Issue by gcheng** [Azure/azure-content#1013]
on this page 
http://msdn.microsoft.com/en-us/library/windowsazure/hh690944.aspx

When customer follow the instruction on the above page, they run into error. 
http://stackoverflow.com/questions/15233037/infinity-loop-in-starting-a-role-instance-in-windows-azure-emulator-waworkerho

**Comment by deneha** [comment]
@gcheng Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
