### ISSUE TITLE
[Media Services] Adding Dynamic Packaging video for MSDN page 

### ISSUE THREAD

**Issue by mingfeiy** [Azure/azure-content#1024]
We recently have a new video to introduce dynamic packing(http://channel9.msdn.com/Series/Windows-Azure-Media-Services-Tutorials/Introduction-to-dynamic-packaging). Could I link the video on the right side of msdn page (http://msdn.microsoft.com/en-us/library/windowsazure/jj889436.aspx).

**Comment by deneha** [comment]
@mingfeiy Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
