### ISSUE TITLE
Refresh SQL Server Getting Started and Provisioning topics

### ISSUE THREAD

**Issue by Selcin** [Azure/azure-content#1027]
I just updated these two topics to give links to Windows Azure Scoped library topics. And I also fixed one bug. 
http://www.windowsazure.com/en-us/manage/windows/common-tasks/install-sql-server/
http://www.windowsazure.com/en-us/manage/windows/common-tasks/sql-server-on-a-vm/
Please stage them and send me a link for review. Thanks.

**Comment by deneha** [comment]
@Selcin Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
