### ISSUE TITLE
Updates to Git Publishing tutorial for Kudu

### ISSUE THREAD

**Issue by timamm** [Azure/azure-content#1080]
Please publish asap in time for AUX 3.2.

The "Publishing a web site with Git" tutorial has been updated to reflect the new UI with new screenshots and content. Since the scope of the tutorial now encompasses Dropbox and Mercurial in addition to Git, GitHub, BitBucket, and CodePlex, the title has changed to "Publishing from Source Control to Windows Azure Web Sites."

**Comment by deneha** [comment]
@timamm Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
