### ISSUE TITLE
Add samples to iOS / Android samples pages

### ISSUE THREAD

**Issue by ChrisRisner** [Azure/azure-content#1094]
I just released a sample for iOS and Android related to accessing Table and Blob Storage through Mobile Services.  Can the following be added to the appropriate pages:

Name:  Connecting to Storage
 
iOS - https://github.com/WindowsAzure-Samples/iOS-MobileServices-Storage
Description:
This sample demonstrates how you can make use of Windows Azure Table and Blob Storage from an iOS app using Mobile Services as a proxy layer.  This means you can securely access tables and blobs through Mobile Services instead of needing to store the storage account key in your client side code.  This sample also shows how to generate a Shared Access Signature in your Mobile Service and return that to the iOS app which can then use it to safely upload an image to Blob Storage.
 
 
 Android - https://github.com/WindowsAzure-Samples/Android-MobileServices-Storage
Description:
This sample demonstrates how you can make use of Windows Azure Table and Blob Storage from an Android app using Mobile Services as a proxy layer.  This means you can securely access tables and blobs through Mobile Services instead of needing to store the storage account key in your client side code.  This sample also shows how to generate a Shared Access Signature in your Mobile Service and return that to the Android app which can then use it to safely upload an image to Blob Storage.

**Comment by deneha** [comment]
@ChrisRisner Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
