### ISSUE TITLE
Refresh SQL Server Getting Started, Provisioning topics; and also 11 screenshots for IAAS GA

### ISSUE THREAD

**Issue by Selcin** [Azure/azure-content#1122]
I updated the SQL Server Getting Started and Provisioning topics for IAAS GA. I also updated 11 screenshots based on the latest changes at WA.com portal. Please make sure that all these changes go live on IAAS GA date not before. I also would like to get a link to staging so that I review my topics. Thanks!

**Comment by deneha** [comment]
@Selcin Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
