### ISSUE TITLE
use the latest version of Windows Azure SDK for Java in maven depdency

### ISSUE THREAD

**Issue by gcheng** [Azure/azure-content#1124]
according to this article, we can use LATEST as the version number of the maven dependency. 

http://stackoverflow.com/questions/30571/how-do-i-tell-maven-to-use-the-latest-version-of-a-dependency

**Comment by deneha** [comment]
@gcheng Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
