### ISSUE TITLE
complete the services we have documentation on Java Developer Guide

### ISSUE THREAD

**Issue by gcheng** [Azure/azure-content#1143]
Many services Java SDK support do not appear on the left bar of Java Developer Guide 
http://msdn.microsoft.com/en-us/library/windowsazure/hh690943(VS.103).aspx
![JavaDevGuide](https://f.cloud.github.com/assets/1541773/373994/ffada05c-a391-11e2-90a2-48494198739d.JPG)

**Comment by deneha** [comment]
Thank you for the suggestion.  It appears this issue is out of date.  Please let us know if you still see a problem.
