### ISSUE TITLE
Clarify the CloudConfigurationManager retrieves AppSettings but not ApplicationSettings

### ISSUE THREAD

**Issue by mohitsriv** [Azure/azure-content#117]
Details:

http://stackoverflow.com/questions/11611404/cloudconfigurationmanager-does-not-pick-up-applicationsettings-from-app-config

**Comment by deneha** [comment]
@mohitsriv Thank you for your question.  I apologize for the delay in reply.  Could you please give us a little more information on your question so that I can contact the correct subject matter expert for you?

**Comment by squillace** [comment]
@mohitsriv Hi Mohit -- I think we can close this one, probably -- otherwise, it can go to @tdykstra or @RickAndMSFT probably for a quick review to see whether it's still operative or undocked.

**Comment by deneha** [comment]
@mohitsriv We're waiting to hear from you to find out if this is still an issue.  Please comment to let us know if you still need help.

**Comment by tdykstra** [comment]
@Thraka - do you cover cloud services / do you know where this notification regarding applicationSettings not being supported should go?

**Comment by mohitsriv** [comment]
It looks like this is documented properly here: https://msdn.microsoft.com/en-us/library/microsoft.windowsazure.cloudconfigurationmanager.aspx.  So, we can close unless there are any other key CloudConfigurationManager docs.

**Comment by deneha** [comment]
@mohitsriv Thanks for letting us know!  I've closed the issue.  Please comment if you need us to reopen the issue.
