### ISSUE TITLE
Update Subscription should have been mentioned in Subscription

### ISSUE THREAD

**Issue by gcheng** [Azure/azure-content#1172]
http://msdn.microsoft.com/en-us/library/windowsazure/hh780765.aspx

![updateSubscription](https://f.cloud.github.com/assets/1541773/398598/8791854c-a85b-11e2-9af1-728d967654f5.png)

**Comment by deneha** [comment]
@gcheng Thank you for the suggestion.  I've forwarded the change to the author of that page.

**Comment by sethmanheim** [comment]
This issue was so old by the time it was assigned to me that the problem no longer exists. Close it.

**Comment by deneha** [comment]
@gcheng Thanks for raising this issue.  It appears that the change is no longer necessary.  Please let us know if there is still a problem by commenting on this issue.  We're going to close this issue unless we hear otherwise from you.
