### ISSUE TITLE
The formatting issue in http://www.windowsazure.com/en-us/manage/services/hdinsight/

### ISSUE THREAD

**Issue by mumian** [Azure/azure-content#1173]
The first letter in the titles needs to be capitalized:

Guidance: What version of Hadoop is in Windows Azure HDInsight?
Tutorial: Simple recommendation engine using Apache Mahout
Tutorial: Using HDInsight to process Blob Storage data and write the results to a SQL Database

**Comment by deneha** [comment]
@mumian Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
