### ISSUE TITLE
New Videos for Windows Phone Tutorial Pages on wa.com

### ISSUE THREAD

**Issue by nickharris** [Azure/azure-content#1197]
<a name="target-page-for-new-windows-phone-content" />
## Target Page for New Windows Phone Content:  ##

Please update the Windows Azure tutorial summary page for Windows Phone with the videos in the next section.  i.e update the WP tutorials page to have similar layout to as the windows store tutorial page (http://www.windowsazure.com/en-us/develop/mobile/resources/)

Target Windows Phone tutorial summary page:

- live: http://www.windowsazure.com/en-us/develop/mobile/resources-wp8/
- stage: http://content-ppe.windowsazure.com/en-us/develop/mobile/resources-wp8/

In addition videos should appear on each of the individual tutorials dedicated page.  E.g http://www.windowsazure.com/en-us/develop/mobile/tutorials/get-started/

<a name="new-windows-phone-videos" />
## New Windows Phone Videos:  ##

<a name="getting-started-with-mobile-services" />
### Tut/Video: Getting Started with Mobile Services ###

- Fwd Link: http://go.microsoft.com/fwlink/?linkid=290816&clcid=0x409
- Current Source: http://channel9.msdn.com/Series/Windows-Azure-Mobile-Services/Windows-Phone-Getting-Started-With-Windows-Azure-Mobile-Services 
- statics
	- medium: http://media.ch9.ms/ch9/ca8a/90322a90-f9d5-424f-9628-bf9e48b3ca8a/CreateYourFirstAppMobileServicesWindowsPhone_220.jpg
   
	- large: http://media.ch9.ms/ch9/ca8a/90322a90-f9d5-424f-9628-bf9e48b3ca8a/CreateYourFirstAppMobileServicesWindowsPhone_512.jpg

<a name="getting-started-with-data" />
### Tut/Video: Getting Started with Data ###

- Fwd Link:  http://go.microsoft.com/fwlink/?LinkID=298628&clcid=0x409
- Source: http://channel9.msdn.com/Series/Windows-Azure-Mobile-Services/Windows-Phone-app-Getting-Started-with-Data-Connecting-your-app-to-Windows-Azure-Mobile-Services
- statics
	- medium: http://media.ch9.ms/ch9/af14/9cb9d374-1bde-4d2e-ae1c-87233e57af14/WindowsPhoneGettingStartedWithData_220.jpg     
	- large:  http://media.ch9.ms/ch9/af14/9cb9d374-1bde-4d2e-ae1c-87233e57af14/WindowsPhoneGettingStartedWithData_512.jpg

<a name="tutvideo-validate-and-modify-data-with-server" />
### Tut/Video: Validate and Modify Data with Server Scripts ###

- Fwd Link: http://go.microsoft.com/fwlink/?LinkId=298629 
- Source: http://channel9.msdn.com/Series/Windows-Azure-Mobile-Services/Windows-Phone-Validate-and-Modify-Data-with-Server-Scripts-in-Windows-Azure-Mobile-Services 
- statics
	- medium: http://media.ch9.ms/ch9/747e/9869c38a-1269-4dc0-b5de-451768b8747e/WPValidatingAndModifyingData_220.jpg 
   
	- large: http://media.ch9.ms/ch9/747e/9869c38a-1269-4dc0-b5de-451768b8747e/WPValidatingAndModifyingData_512.jpg 

<a name="getting-started-with-authentication" />
### Tut/Video: Getting Started with Authentication ###

- Fwd Link:  http://go.microsoft.com/fwlink/?LinkId=298631
- Source:  http://channel9.msdn.com/Series/Windows-Azure-Mobile-Services/Windows-Phone-Getting-Started-with-Authentication-in-Windows-Azure-Mobile-Services
- statics
	- medium: http://media.ch9.ms/ch9/a4fd/1e93823a-b99e-4edc-b5f5-c1998c17a4fd/WPGettingStartedWithAuthentication_220.jpg     
	- large:  http://media.ch9.ms/ch9/a4fd/1e93823a-b99e-4edc-b5f5-c1998c17a4fd/WPGettingStartedWithAuthentication_512.jpg

<a name="tutvideo-authenticate-and-authorize-users-wit" />
### Tut/Video: Use scripts to authorize users  ###

- Fwd Link: http://go.microsoft.com/fwlink/?LinkId=298630 
- Source:  http://channel9.msdn.com/Series/Windows-Azure-Mobile-Services/Windows-Phone-Authenticate-and-Authorize-users-with-Server-Scripts-in-Windows-Azure-Mobile-Services
- statics
	- medium: http://media.ch9.ms/ch9/14d4/3f8b3f70-2190-4d16-a5a3-732b434414d4/WPAuthenticateAndAuthorizeUsers_220.jpg    
	- large: http://media.ch9.ms/ch9/14d4/3f8b3f70-2190-4d16-a5a3-732b434414d4/WPAuthenticateAndAuthorizeUsers_512.jpg 

Thanks,
Nick Harris

**Comment by deneha** [comment]
@nickharris Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
