### ISSUE TITLE
[Media Services] Adding Release note link besides banner 

### ISSUE THREAD

**Issue by mingfeiy** [Azure/azure-content#1218]
http://www.windowsazure.com/en-us/develop/media-services/ 

The link should be pointing to: http://msdn.microsoft.com/en-us/library/windowsazure/jj884319.aspx

**Comment by deneha** [comment]
@mingfeiy Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
