### ISSUE TITLE
[Media Services] Adding GitHub release banner for 5/17

### ISSUE THREAD

**Issue by mingfeiy** [Azure/azure-content#1219]
We are going to release .NET SDK source code latest 5/17. And we should move the fifth banner forward to the 2nd and make it showing .NET SDK and JAVA SDK together.

**Comment by deneha** [comment]
@mingfeiy Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
