### ISSUE TITLE
Add Windows Phone Samples page to Mobile Services Dev Center

### ISSUE THREAD

**Issue by nickharris** [Azure/azure-content#1244]
This issue adds a new Samples Page to the Mobile Services devcenter for Windows Phone

### Add Samples Link to Left Nav Bar when Windows Phone is selected ###
> https://www.windowsazure.com/en-us/develop/mobile/tutorials/get-started-with-users-wp8/
i.e should have samples link similar to when W8 is selected https://www.windowsazure.com/en-us/develop/mobile/tutorials/get-started-with-users-dotnet/

#### Sample 1 ####
- Title: Storing and Retrieving Data off device with Mobile Services in your Windows Phone app
- Summary: This sample demonstrates how you can quickly store and access data from your Windows Phone app off device in a cloud service using Windows Azure Mobile Services.
- Link: http://code.msdn.microsoft.com/Get-Started-with-Data-in-5d10271f

#### Sample 2 ####

- Title:  Authenticate users of your Windows Phone app using Microsoft Account, Facebook, Twitter & Google with Mobile Services
- Summary: This sample demonstrates how you can easily wire up your Windows Phone application to require your users to Authenticate against well know social identity providers such as Microsoft Account, Facebook, Twitter and Google using Windows Azure Mobile Services.
- Link: http://code.msdn.microsoft.com/windowsazure/WP-Authenticate-Account-c7e0ef84

kind regards,
nick

**Comment by deneha** [comment]
@nickharris Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
