### ISSUE TITLE
Web sites updates for release on May 8

### ISSUE THREAD

**Issue by timamm** [Azure/azure-content#1260]
Updated  "howto-configure-websites.md" handler mappings description per RD781084.

Updated the following web-related pages to change "Preview Management Portal" to "Windows Azure Management Portal":
create-php-website.md
deployWAWebSiteThatConnectsToMongo.md
website-mysql.md
website-mysql-ftp.md
website-mysql-git.md
website-sqlazure-git.md
website-storage.md
web-site-with-sql.md

**Comment by deneha** [comment]
@timamm  Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
