### ISSUE TITLE
Create topics that ref 3 new Mooncake chunks

### ISSUE THREAD

**Issue by pennij** [Azure/azure-content#1277]
Chunk topics were created by Ben Lobaugh in this PR on 5-2-13: https://github.com/WindowsAzure/azure-content/pull/1272/files 

Chunks were staged on sandbox-ppe to be included in loc drop week of 5-6-13.

Need to create all the topic stubs that will reference these 3 chunk, and get the topics pub'd on wa.com.

See email thread from May 2 2013 w/ Ben, Doug Mahugh, Molly, and Penni

**Comment by deneha** [comment]
@pennij Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
