### ISSUE TITLE
Add Tamra's new and updated topics to upcoming release

### ISSUE THREAD

**Issue by pennij** [Azure/azure-content#1377]
NOTE: See one email thread between Susan and Penni, Friday 5-24-13, 2.41pm, for partial info.

Here's Tamra's pull req with updates (will need to change Milestone date to appropriate date and maybe ask Sasha to publish the updates to sandbox in case it gets 'missed' since pull req was created a week or so ago).

https://github.com/WindowsAzure/azure-content/pull/1307

**Comment by deneha** [comment]
@pennij Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
