### ISSUE TITLE
Update links in http://www.windowsazure.com/en-us/develop/net/data/

### ISSUE THREAD

**Issue by tdykstra** [Azure/azure-content#1397]
Two links are out of date:

1. Create and deploy an ASP.NET web site and SQL Database with Visual Studio.

    Change title to "Deploy a Secure ASP.NET MVC app with Membership, OAuth, and SQL Database to a Windows Azure Web Site"
Change blurb to: "Implement an ASP.NET MVC 4 web application that uses SQL Server and enables users to log in with credentials from Facebook, Yahoo, and Google. You will also deploy the application to Windows Azure and SQL Database."

2. Create and deploy a cloud service and SQL Database with Visual Studio.

    Delete this link and its associated blurb text.  The link points to the same target as the " .NET Multi-Tier Application Using Storage Tables, Queues, and Blobs" in the Azure Storage section.

**Comment by deneha** [comment]
@tdykstra Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
