### ISSUE TITLE
Retire WA.com monitoring SQL Database topic, move its content to library topic.

### ISSUE THREAD

**Issue by tysonn** [Azure/azure-content#1415]
The existing "monitoring SQL Database" topic should be retired from WA.com as it is functionally just a manual redirect topic. http://www.windowsazure.com/en-us/manage/services/sql-databases/how-to-monitor-a-sqldb/

Incorporate the little content from the page into the main monitoring topic in the library, which is at http://msdn.microsoft.com/en-us/library/windowsazure/ff394114.aspx.

Editor has already made the SQL DB page point directly to the library topic.

Coordinate removal of topic from GitHub with editor so the WAcom page in Umbraco is also deleted.

**Comment by jeffgoll** [comment]
Please remove this article. It's useless.

**Comment by jeffgoll** [comment]
The article has been removed. This issue can be closed. Thanks!
