### ISSUE TITLE
Create Virtual Machine Deployment documentation has wrong casing for Fingerprint

### ISSUE THREAD

**Issue by huguesv** [Azure/azure-content#1461]
The sample and description have typos.  It should be Fingerprint everywhere, with a lowercase p.  And if you find/replace, don't miss FinguerPrint...

```
          <SSH>
            <PublicKeys>
              <PublicKey>
                <FingerPrint>certificate-fingerprint</FingerPrint>
                <Path>SSH-public-key-storage-location</Path>     
              </PublicKey>
            </PublicKeys>
            <KeyPairs>
              <KeyPair>
                <FingerPrint>certificate-fingerprint</FinguerPrint>
                <Path>SSH-public-key-storage-location</Path>
              </KeyPair>
            </KeyPairs>
          </SSH>

```

and

FingerPrint
 
Required. Specifies the SHA1 fingerprint of an X509 certificate associated with the hosted service that includes the SSH public key.
 
and

FingerPrint
 
Required. Specifies the SHA1 fingerprint of an X509 certificate associated with the hosted service that includes the SSH keypair.

**Comment by huguesv** [comment]
Several of the documentation bugs that I filed against the REST API are getting closed in the past few days with no explanation.  I'm looking at the page:
https://msdn.microsoft.com/en-us/library/azure/jj157194.aspx
and it doesn't look like it's been fixed.  Still says 'FingerPrint' instead of 'Fingerprint' for the xml element.
So why is it getting closed?

**Comment by squillace** [comment]
@deneha Dene, this one got closed incorrectly as well. Please reopen, and I think we may need to review the closures a bit.

@huguesv Sorry about that -- it was inadvertently closed.

**Comment by deneha** [comment]
@huguesv @squillace Apologies.  I've reopened the issue.

**Comment by squillace** [comment]
@huguesv Now that you have me looking at this, can you provide the URL that you're looking at here? Otherwise, I have no idea which document you're filing the issue about..... :-)

**Comment by huguesv** [comment]
Yeah, sorry, I hadn't included it in the original post.  It's https://msdn.microsoft.com/en-us/library/azure/jj157194.aspx

**Comment by squillace** [comment]
No worries. I'll see about finding the author. Appreciate it.

**Comment by davidmu1** [comment]
The element should be Fingerprint and the topic has been corrected. Thank you for your feedback.

**Comment by deneha** [comment]
@huguesv The issue appears to have been corrected.  We're closing this issue.  Please comment if you need the issue to be reopened for any reason.
