### ISSUE TITLE
Add a link to the server scripts API content in the Zumo reference pages

### ISSUE THREAD

**Issue by ggailey777** [Azure/azure-content#1464]
We need to add a link to Mobile Services server script reference (http://msdn.microsoft.com/en-us/library/windowsazure/jj554226.aspx) from the main Zumo reference topic (http://www.windowsazure.com/en-us/develop/mobile/reference/) and in each platform-specific reference page as well.

This is a customer reported issue (Mike Taulty).

**Comment by deneha** [comment]
@ggailey777 Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
