### ISSUE TITLE
Problem with jumping to a subtitle within an article

### ISSUE THREAD

**Issue by mumian** [Azure/azure-content#1474]
This issue applies to all of the articles on wa.com.  Let's using the following article as an example:

http://www.windowsazure.com/en-us/manage/services/hdinsight/introduction-hdinsight/

Click on a subtitle on the navigation bar on the left, notice the subtitle and first a few lines are missing.

**Comment by deneha** [comment]
@mumian Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
