### ISSUE TITLE
Remove links to Load Test topics for Matt

### ISSUE THREAD

**Issue by pennij** [Azure/azure-content#1489]
For details, see email thread on 7-16 at 2.26pm. Fix for next release.

Delete one sentence in this topic:  http://www.windowsazure.com/en-us/develop/net/architecture/load-testing-pattern/

Delete one para in this topic:  http://www.windowsazure.com/en-us/develop/net/guidance/

**Comment by deneha** [comment]
@pennij Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
