### ISSUE TITLE
wrong link address on the HDInsight landing page

### ISSUE THREAD

**Issue by mumian** [Azure/azure-content#1502]
This error is on this page:

http://www.windowsazure.com/en-us/documentation/services/hdinsight/

Click See More under the Analyze section.
Click Use the Hadoop .NET SDK with the HDInsight Service.  
The correct URL is:

http://www.windowsazure.com/en-us/manage/services/hdinsight/howto-net-libraries/

**Comment by deneha** [comment]
@mumian Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
