### ISSUE TITLE
add support of get and list to media services notification end point

### ISSUE THREAD

**Issue by gcheng** [Azure/azure-content#1510]
http://msdn.microsoft.com/en-us/library/windowsazure/dn169055.aspx 

from George 

Yes. There is support for list and get. I guess we are missing documentation.
You should be able to get this operation through general ODATA REST notation similar to other entities

GET “API/NotificationEndPoints”

**Comment by deneha** [comment]
@gcheng Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
