### ISSUE TITLE
Add references to CLI and PowerShell articles from the Windows Azure UI management how-to articles

### ISSUE THREAD

**Issue by mumian** [Azure/azure-content#1518]
For example.  On this article:

http://www.windowsazure.com/en-us/manage/services/storage/how-to-create-a-storage-account/

reference the following articles:
For a general guide on how to use the command-line interface, see [How to use the Windows Azure Command-Line Tools for Mac and Linux](/en-us/develop/nodejs/how-to-guides/command-line-tools/). For comprehensive reference documentation, see [Windows Azure command-line tool for Mac and Linux](/en-us/manage/linux/other-resources/command-line-tools/). This article only covers using the command-line interface from Windows.

**Comment by deneha** [comment]
@mumian Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
