### ISSUE TITLE
Adding Windows Azure Multi-Factor Authentication What is Page

### ISSUE THREAD

**Issue by billmath** [Azure/azure-content#1537]
Team Project Collection: 	vstfpg05\PG05 
TFS item http://vstfpg05:8080/tfs/web/wi.aspx?pcguid=4a427888-16eb-489e-a913-f920fdbf5ca6&id=243839

**Comment by deneha** [comment]
@billmath Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
