### ISSUE TITLE
Error in "How to install and configure Windows Azure PowerShell"

### ISSUE THREAD

**Issue by mumian** [Azure/azure-content#1570]
http://www.windowsazure.com/en-us/manage/install-and-configure-windows-powershell/

The default path is not:

C:\Users\<UserProfile>\Desktop\[MySubscription-…]-downloadDate-credentials.publishsettings

but:

C:\Users\<UserProfile>\Download\[MySubscription-…]-downloadDate-credentials.publishsettings

**Comment by deneha** [comment]
@mumian Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
