### ISSUE TITLE
CDN 

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-content#1731]
On https://github.com/WindowsAzure/azure-content/blob/master/includes/cdn.md

It says there's a CDN option on the left sidebar of the management panel. There isn't.

>1.In the Azure Management Portal, in the navigation pane, click CDN.
>2.On the ribbon, click New. In the New dialog, select App Services, then CDN, then Quick Create.

**Comment by deneha** [comment]
@v-aljenk Sent mail to ask status.

**Comment by ahmetalpbalkan** [comment]
@deneha rule of thumb while operating in open source: You usually provide a status/reason about why you are closing the issue. An issue reporter usually does not care who you sent email to, they care if the issue they spent time reporting is:

* invalid (i.e. not an issue)
* fixed
* wontfix

Please appreciate the time the person has spent on the issue and provide a status back.

It's not a problem for me. I don't care about CDN or Azure docs, that's not my job. I don't care if you close the status without a message, but if I was a customer I'd be frustrated. So please do not do this.

**Comment by squillace** [comment]
@deneha Yeah, Dene, please reopen this issue. This is a storage documentation issue -- have @tamram take a look. @ahmetalpbalkan is merely reporting it, and we don't close until the issue has resolution.

**Comment by deneha** [comment]
@ahmetalpbalkan @squillace Apologies.  In the midst of a bulk issue cleanup.  The issue has been reopened.

**Comment by squillace** [comment]
@deneha Great, thanks. :-) Careful with that bulk closure algorithm!

**Comment by tysonn** [comment]
Sent to doc owner for review.

**Comment by Juliako** [comment]
It could be that when the ticket was opened the CDN was not enabled for that account. After April 2014, CDN was enabled for everyone. Please try locating it now.
![cdnimage](https://cloud.githubusercontent.com/assets/1652984/9076490/a65f4412-3ad7-11e5-89e2-cca6db1b5115.PNG)

**Comment by davidwrede** [comment]
Hi @ahmetalpbalkan, apologies for the very long delay! 

Our CDN provisioning topic has been updated [here](https://azure.microsoft.com/en-us/documentation/articles/cdn-create-new-endpoint/). I just went through the steps again to verify that CDN is available in the left sidebar, so if you're still not seeing it, then I'm happy to drill down with you further to try and figure out what the problem might be.

Thanks,
Dave

**Comment by ahmetalpbalkan** [comment]
@davidwrede np at all!

After more than a year, I learned that we shut down our CDN service to new customers (and I was a new customer back then). If you actually sign up for an Azure account using your credit card, I think CDN service still does not exist on the left sidebar...

So I think docs still are invalid.

**Comment by zhangmanling** [comment]
CDN is by default enabled in left navigation for all customers. Please provide the subscription ID that you see the problem.

**Comment by ahmetalpbalkan** [comment]
@zhangmanling I don't have a subscription that CDN was not enabled. But I had to open a support ticket to get CDN enabled on my subscription last year. Closing this issue assuming it's fixed now... Thanks.
