### ISSUE TITLE
[cloud-services-python-how-to-use-service-management] Management Certificates

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/azure-content#1738]
The section of the article **cloud-services-python-how-to-use-service-management** on **Connect to Service Management** explains how to generate management certificates. This is valuable information, however, with the use of the cross platform tools it is possible to simply many of these steps.

If someone downloads the Windows Azure Cross Platform Tools a Management Certificate is made on their behalf in their subscription. They can export a client certificate in a `*.pem` format by running the following command.

`azure account cert export`

The subscription name can be passed in as an optional parameter, if it isn't provided the user is prompted to select which subscription to export a certificate for.

**Comment by huguesv** [comment]
Thanks for the tip, I actually didn't know about this :)

We'll make sure to add this for the next doc update.

**Comment by deneha** [comment]
It appears this issue has been resolved in https://github.com/Azure/azure-sdk-for-python/issues/376 - please comment if I should reopen this issue.
