### ISSUE TITLE
Link to retired topic needs to be fixed in web-sites-dotnet-get-started-vs2012.md 

### ISSUE THREAD

**Issue by tysonn** [Azure/azure-content#1812]
The link to http://msdn.microsoft.com/en-us/library/windowsazure/jj218759.aspx needs to be replaced with a link to http://azure.microsoft.com/en-us/documentation/articles/choose-web-site-cloud-service-vm/. The MSDN topic has been retired.

**Comment by deneha** [comment]
Link has been replaced
