### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by Photekk** [Azure/azure-content#1862]
Not sure if this is the right place to ask this question but will the "Notify users with Notification Hubs" tutorial ever include Android?

**Comment by deneha** [comment]
@Photekk Thank you for your question.  I apologize for the delay in reply.  Could you please give us a little more information on your question so that I can contact the correct subject matter expert for you?

**Comment by deneha** [comment]
@davidwrede Could you please assist?

**Comment by davidwrede** [comment]
Hi @Photekk, we have an Android version of this content posted here: https://azure.microsoft.com/en-us/documentation/articles/notification-hubs-aspnet-backend-android-notify-users/. If this tutorial isn't what you were looking for, feel free to leave a comment in the Disqus thread and we can follow up on how to make the content more useful.

Thanks,
Dave
