### ISSUE TITLE
Service API Sample code not working (for linux VMs)

### ISSUE THREAD

**Issue by morgs32** [Azure/azure-content#1928]
I'm trying to run the example you have provided here: https://github.com/Azure/azure-content/blob/master/articles/virtual-machines-linux-how-to-service-api.md

And I'm getting back this error:
{ [Error: A computer name must be specified.]

  code: 'BadRequest',

  statusCode: 400,

  requestId: '5aa7622950e5c7c1affdec1bda51d27d' }

And I know that I'm sending a computer name in the configuration set (it's in the sample code!).

**Comment by deneha** [comment]
@morgs32 Thank you for your question.  Very sorry for the delay in our reply.  Is there still a problem?

**Comment by deneha** [comment]
@morgs32 I'm closing this issue because that page has been removed and replaced with updated content.  Please let us know if you still need assistance.

**Comment by morgs32** [comment]
@deneha thanks for asking - sorry for not responding. where is the updated content?

**Comment by deneha** [comment]
@morgs32 Correction - our log shows this page was deleted.  I'll contact the author of the old page for you and see what information I can get.

**Comment by morgs32** [comment]
@deneha thanks, much appreciated.

**Comment by deneha** [comment]
@morgs32 Sorry about the issue close.  It has been reopened.  I've heard from the last person who touched the page.  I'll get back to you as soon as I hear more.

**Comment by KBDAzure** [comment]
Hi @morgs32 - I'm sorry to report that I haven't been able to locate similar content. The article that was deleted because we 'retired' the article. There have been many changes to Azure in the last year, so it's likely that the content wasn't accurate.

**Comment by deneha** [comment]
@morgs32 If you need more help or have additional questions, please feel free to open another issue or comment on this issue to be reopened.  We're closing this issue for now since we haven't heard from you.
