### ISSUE TITLE
Deployment Instructions do not work.

### ISSUE THREAD

**Issue by ninajlu** [Azure/azure-content#1929]
https://github.com/Azure/azure-content/blob/master/articles/virtual-machines-python-use-mysql-django.md
This instructs the user to type this:
PS C:\django\helloworld> $ipPort = 
PS C:\django\helloworld> $ipPort = [string]$ipPort.AddressList[1]
PS C:\django\helloworld> $ipPort += ":80"
PS C:\django\helloworld> C:\Python27\python.exe .\manage.py runserver $ipPort

but the first line is incomplete as powershell is looking for something to complete the equation. Thus the next line can not work since there is no AddressList of $ipPort. 
Can you instruct on how to fix this?

**Comment by deneha** [comment]
@ninajlu Thank you for your question.  We're really sorry about the delay in response.  Are you still experiencing a problem?

**Comment by deneha** [comment]
@ninajlu We're reviewing old issues and closing them. If this issue should not be closed, please let us know so that we can reopen it and assign it to the proper person.
