### ISSUE TITLE
Code generated by Visual Studio push notification wizard produces invalid JSON response

### ISSUE THREAD

**Issue by jkkjonah** [Azure/azure-content#1946]
The Node.js sample code for "notifyAllUsers" endpoint that's generated by the push notification wizard produces an invalid JSON response (simply responds with the string "OK"). This causes the MobileServiceClient.InvokeApiAsync throws an exception when parsing the response. The line:

    response.send(statusCodes.OK);

should be:

    response.send(statusCodes.OK, { status : 'OK' });

**Comment by deneha** [comment]
@davidwrede Sent mail for status.

**Comment by davidwrede** [comment]
@kempb, could either you or Patrick look into this and see if it's still an issue?

Thanks,
Dave

**Comment by patshea123** [comment]
I created a Win8 app in VS 2015, added Moblie Services through the *Add Connected Services* dialog, then added Push Notifications through the [Project] / Add / Push Notifications wizard.

 - The generated notifyallusers.js file still contains the code 
        response.send(statusCodes.OK);
- The Windows Dev Center Win8 archived topic [Code generated by the push notification wizard](https://msdn.microsoft.com/en-us/library/windows/apps/dn263179.aspx) referenced in the notifyallusers.js file
    // See documentation at http://go.microsoft.com/fwlink/?LinkId=296704&clcid=0x409
is different from both the actual and suggested code in this bug.

I will attempt to contact the appropriate people to see 
 - What the correct code is
 - Whether the generate code can be corrected if necessary
 - Whether the archived WDC can be updated

Patrick

My apologies if the Markdown is not correct.

**Comment by deneha** [comment]
@jkkjonah It appears that the question has been answered.  I'm going to close this issue now.  Please comment if we should reopen this issue and investigate further.
