### ISSUE TITLE
Is Custom Linux VM image x86 and X64 both are supported on azure 

### ISSUE THREAD

**Issue by aageek** [Azure/azure-content#2001]
On following article we are missing the detail about supported architecture (x86 or x64) for Linux image support on Azure or not . 

Creating and Uploading a Virtual Hard Disk that Contains the Linux Operating System -  http://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-create-upload-vhd/ 

Please add support Architecture for Custom Linux VM on Azure -  Similar to Windows as in below article . - http://azure.microsoft.com/en-us/documentation/articles/virtual-machines-create-upload-vhd-windows-server/ 
Window Server operating system media. This task requires an .iso file that contains the Windows Server operating system. The following Windows Server versions are supported:

OS     SKU   Service Pack      Architecture
Windows Server 2012 R2   -- All editions -- N/A  --x64 
Windows Server 2012  -- All editions  --- N/A  --x64 
Windows Server 2008 R2 -- All editions -- SP1 -- x64

**Comment by deneha** [comment]
@aageek Thank you for raising this issue.  We're sorry for the delay in response.  We're reviewing old issues and closing them. If this issue should not be closed, please let us know so that we can reopen it and assign it to the proper person.
