### ISSUE TITLE
WACOM.NOTE appears in rendered html for php service bus how to guide

### ISSUE THREAD

**Issue by huguesv** [Azure/azure-content#2008]
http://azure.microsoft.com/en-us/documentation/articles/service-bus-php-how-to-use-topics-subscriptions/

in the section named 'Configure your application to use Service Bus', there's a suspicious WACOM.NOTE that is formatted as code.

**Comment by deneha** [comment]
Thanks for the tip!  We've notified the author.

**Comment by huguesv** [comment]
FYI: This is still an issue. Slightly different than it used to be (AZURE.NOTE instead of WACOM.NOTE).  Open that page in your browser and search for `<!--AZURE.NOTE-->`, you'll find 3 instances of it.

**Comment by sethmanheim** [comment]
OK to merge.

**Comment by sethmanheim** [comment]
Fixed.

**Comment by deneha** [comment]
@huguesv The page has been fixed.  We're going to close this issue since the page correction will go live at next publishing.  If you still see a problem, please comment and we'll reopen the issue.  Thanks again for raising the issue!
