### ISSUE TITLE
Azure Service Bus no longer offers "Add Metrics" option

### ISSUE THREAD

**Issue by hydrojumbo** [Azure/azure-content#2036]
On this documentation, it suggests the presence of a button that does not exist today - Add Metrics for an Azure Service Bus Queue: https://github.com/Azure/azure-content/blob/master/articles/service-bus-monitor-message-entities.md

My requirement is to set up alarms based on Max Queue Length in the last N Minutes. Is this no longer supported?

**Comment by deneha** [comment]
@sethmanheim Can you take a look at this?

**Comment by sethmanheim** [comment]
I don't know where this URL is coming from -- maybe his favorites. I don't have this topic in the repo, and the above link gives a 404.

**Comment by deneha** [comment]
Ok, understood.  Closing issue.

**Comment by hydrojumbo** [comment]
I cannot confirm this second, but the URL  is specific to my Azure
Subscription, it is a standard screen within the Azure Management Web
client. I will check to see if the problem still exists and provide
instructions on how to get to the view without a direct URL if it does.

**Comment by sethmanheim** [comment]
OK thanks Alex. Please let us know and we'll see about getting it fixed, but at this time the topic does not exist in our documentation set.
