### ISSUE TITLE
Add "warning" that .Net mobile services don't support Git

### ISSUE THREAD

**Issue by DavidKarlas** [Azure/azure-content#2247]
I think it would be cool to add some kind of warning on this page that this is only supported for JavaScript backend. Or even better, add Git support to .Net backend :)

https://github.com/Azure/azure-content/blob/master/articles/mobile-services-store-scripts-source-control.md

Something similar like this warning:
```
Source control is a preview feature. We recommend that you backup your script files regulary, even though they are stored in Mobile Services.
```

Btw, I just noticed that regularly is misspelled in text above.

**Comment by deneha** [comment]
@davidwrede @DavidKarlas  Do you need this issue to remain open? We're reviewing old issues and closing them. If this issue should not be closed, please let us know so that we can reopen it and assign it to the proper person.

**Comment by DavidKarlas** [comment]
Quick look at documentation page... Looks like .Net backend was added so it can stay closed.
