### ISSUE TITLE
REST API 'Create VM Image' has incorrect request body documentation

### ISSUE THREAD

**Issue by huguesv** [Azure/azure-content#2271]
http://msdn.microsoft.com/en-us/library/azure/dn775054.aspx

Still an issue:
Under the 'Request Body' section, it talks about 'response body' in a couple of places instead of 'request body'.

Fixed:
Additionally (and that's what cost me a lot of time), the xml example under 'Request Body' section is wrong.  The xml root element is a single VMImage, the VMImages element should not be there.

**Comment by davidmu1** [comment]
The corrections have been made to the terminology and the request body example. Thanks you for your feedback

**Comment by deneha** [comment]
@huguesv The issue appears to have been corrected. We're closing this issue. Please comment if you need the issue to be reopened for any reason.
