### ISSUE TITLE
Printer Friendly Articles

### ISSUE THREAD

**Issue by gfeiges** [Azure/azure-content#2365]
I tried printing http://azure.microsoft.com/en-us/documentation/articles/hyper-v-recovery-manager-azure/ directly and it was unreadable.
Had to go into GITHUB edit mode to make a printed copy of the article I could follow.   Is there some  way to ensure that all TechNet articles have a printer friendly version that can be leveraged.

Thanks

**Comment by deneha** [comment]
@gfeiges @plasmaphonic Thank you very much for the suggestion.  I've passed it on to the powers that be and hopefully very soon this problem will be a thing of the past.  I'm going to close this issue now, but please do request it be reopened if you feel the need.
