### ISSUE TITLE
XAMARIN Android - Azure Mobile Service Push Notification Problem

### ISSUE THREAD

**Issue by jx37** [Azure/azure-content#2391]
Hi,
I’m  developing an app that receive push notification from Azure Mobile Service in Xamarin-Android.
When I start the application I register my device (Nexus 4) to my Azure Notification Hub.
Push Notification still received only when app is running or is in background, but not when the app is closed or I delete it from task manager (N.B I don’t force to quit it from settings).

Below the class:

PushNotificationService.cs & PushGcmBroadcastReceiver.cs

using System;
//using WindowsAzure.Messaging;
using Android.App;
using Android.Content;
using Android.OS;
using Cirrious.CrossCore;
using Gcm;
using Microsoft.WindowsAzure.MobileServices;
using Telecom.MyTickets.Android.Views;
using Telecom.MyTickets.Core.PCL.Data;
using Telecom.MyTickets.Core.PCL.Interfaces;
using ByteSmith.WindowsAzure.Messaging;
using Debug = System.Diagnostics.Debug;

[assembly: Permission(Name = "myproject.permission.C2D_MESSAGE")]
[assembly: UsesPermission(Name = "myproject.permission.C2D_MESSAGE")]
[assembly: UsesPermission(Name = "com.google.android.c2dm.permission.RECEIVE")]

//GET_ACCOUNTS is only needed for android versions 4.0.3 and below
[assembly: UsesPermission(Name = "android.permission.GET_ACCOUNTS")]
[assembly: UsesPermission(Name = "android.permission.INTERNET")]
[assembly: UsesPermission(Name = "android.permission.WAKE_LOCK")]

namespace Telecom.MyTickets.Android.Platform
{    
    [Service]
    public class PushNotificationService : GcmServiceBase, IPushNotificationService
    {
        #region Fields
        private static NotificationHub _hub;
        private static Context _context;
        #endregion

        #region MobileServiceClient
        // Use this constructor instead after publishing to the cloud
        public static MobileServiceClient MobileService = new MobileServiceClient(
            "https://devtimmobility.azure-mobile.net/",
            "GnLWUaNgtpyKeVAvqNRILEgaxdvhtU18");
        #endregion

        #region ctor
        public PushNotificationService()
            : base(PushGcmBroadcastReceiver.SenderIds)
        {
        }
        #endregion

        #region IPushNotificationService implementation
        public void Register(string channelName, Action onNotifyReceived, Action onErrorAction)
        {
            Register(_context);
        }

        public void UnRegister(string channelName)
        {
            GcmClient.UnRegister(_context);
        }
        #endregion

        #region GcmServiceBase implementation

        public static void Initialize(Context context)
        {
            _context = context;
            _hub = new NotificationHub(LocalData.NotificationHubName, LocalData.AzureConnectionString);
        }

        public static void Register(Context context)
        {
            GcmClient.CheckDevice(context);
            GcmClient.CheckManifest(context);

            // Makes this easier to call from our Activity
            GcmClient.Register(context, PushGcmBroadcastReceiver.SenderIds);
        }

        protected override void OnRegistered(Context context, string registrationId)
        {
            try
            {
                //Receive registration Id for sending GCM Push Notifications to
                if (_hub == null)
                    return;

                //_hub.UnregisterAll(registrationId);
                _hub.UnregisterAllAsync(registrationId);

                //_hub.Register(registrationId, "test");
                _hub.RegisterNativeAsync(registrationId);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Exception occurred in OnRegistered: {0} - StackTrace: {1}", ex.Message, ex.StackTrace);
            }
        }

        protected override void OnUnRegistered(Context context, string registrationId)
        {
            try
            {
                if (_hub != null)
                    //_hub.Unregister();
                    _hub.UnregisterAllAsync(registrationId);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Exception occurred in OnUnRegistered: {0} - StackTrace: {1}", ex.Message, ex.StackTrace);
            }
        }

        protected override async void OnMessage(Context context, Intent intent)
        {
            Debug.WriteLine("--------- Received Notification ---------");

            //var pm = PowerManager.FromContext(context);
            //var sWakeLock = pm.NewWakeLock(WakeLockFlags.Full | WakeLockFlags.AcquireCausesWakeup, PushGcmBroadcastReceiver.TAG);
            //sWakeLock.Acquire();

            //Push Notification arrived - print out the keys/values
            if (intent == null || intent.Extras == null)
                return;

            var keys = intent.Extras;

            //Get values of toast parameters
            var title = keys.ContainsKey("newsTitle") ? keys.GetString("newsTitle") : string.Empty;
            var message = keys.ContainsKey("newsMessage") ? keys.GetString("newsMessage") : string.Empty;
            var param = keys.ContainsKey("newsId") ? keys.GetString("newsId") : string.Empty;

            var dm = Mvx.GetSingleton<DataManagement>();
            await dm.SaveNewsId(param);

            //Show push notification
            CreateNotification(title, message);

            //sWakeLock.Release();
        }

        protected override bool OnRecoverableError(Context context, string errorId)
        {
            //Some recoverable error happened  
            return base.OnRecoverableError(context, errorId);
        }

        protected override void OnError(Context context, string errorId)
        {
            //Some more serious error happened           
        }

        #endregion

        void CreateNotification(string title, string desc)
        {
            //Create notification
            var notificationManager = GetSystemService(NotificationService) as NotificationManager;

            //Create an intent to show ui
            var uiIntent = new Intent(this, typeof(MainView));
            uiIntent.SetFlags(ActivityFlags.IncludeStoppedPackages);

            const int pendingIntentId = 0;
            var pendingIntent = PendingIntent.GetActivity(this, pendingIntentId, uiIntent, PendingIntentFlags.OneShot);

            // Instantiate the notification builder and enable sound:
            var builder = new Notification.Builder(this)
                .SetContentIntent(pendingIntent)
                .SetContentTitle(title)
                .SetContentText(desc)
                .SetDefaults(NotificationDefaults.Sound)
                .SetSmallIcon(Resource.Drawable.ic_launcher);

            var notification = builder.Build();

            // Publish the notification:
            const int notificationId = 0;
            if (notificationManager != null)
                notificationManager.Notify(notificationId, notification);
        }
    }

    [BroadcastReceiver(Permission = Constants.PERMISSION_GCM_INTENTS)]
    [IntentFilter(new string[] { "com.google.android.c2dm.intent.RECEIVE" }, Categories = new string[] { "myproject" })]
    [IntentFilter(new[] { Constants.INTENT_FROM_GCM_MESSAGE }, Categories = new[] { "myproject" })]
    [IntentFilter(new[] { Constants.INTENT_FROM_GCM_REGISTRATION_CALLBACK }, Categories = new[] { "myproject" })]
    [IntentFilter(new[] { Constants.INTENT_FROM_GCM_LIBRARY_RETRY }, Categories = new[] { "myproject" })]
    public class PushGcmBroadcastReceiver : GcmBroadcastReceiverBase<PushNotificationService>
    {
        public static string SenderId = "MyProjectSenderID";

        //The SENDER_ID is your Google API Console App Project Number
        public static string[] SenderIds = { SenderId };

        public const string TAG = "MyBroadcastReceiver-GCM";
    }
}

Hope you can help me.

**Comment by deneha** [comment]
@davidwrede Has this issue been resolved?

**Comment by davidwrede** [comment]
Hi @jx37, apologies for the delay. We've recently updated the [Xamarin.Android version](https://azure.microsoft.com/en-us/documentation/articles/partner-xamarin-mobile-services-android-get-started-push/) of our push notification tutorial. 

Please check it out, and if you're still stuck, feel free to leave a Disqus comment at the bottom of the topic and we'll respond as soon as we can.

Thanks,
Dave
