### ISSUE TITLE
customer report - issue in cloud service + SQL Database tutorial in VS 2010

### ISSUE THREAD

**Issue by mollybostic** [Azure/azure-content#24]
From Disqus comments on http://www.windowsazure.com/en-us/develop/net/tutorials/cloud-service-with-sql-database (comment by Lee Moore):

I had to delete "User Instance=true;" to get the local deployment to work with VS 2010 and SQL Server Express.

**Comment by deneha** [comment]
@mollybostic Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
