### ISSUE TITLE
Android code does not build/compile.

### ISSUE THREAD

**Issue by boolship** [Azure/azure-content#2401]
1) The following line is WRONG in #12 of  
azure-content/includes/mobile-services-android-getting-started-with-push.md

ToDoActivity.mClient.getPush().register(gcmRegistrationId, null);

Because the register method *requires* three parameters, e.g.
register(String pnsHandle, String [] tags, RegistrationCallback callback)

2) Any suggestions how to fix?

3) The push notification demo is FAIL with this bug.

**Comment by Vol-i** [comment]
Hi, i think the problem is that they updated the sdks but not the demo app. After tackling for a while, it turns out it needs a callback, even if you don't use it. Just create a callback as below and it will be fine.
 
```
mClient.getPush().register(gcmRegistrationId,
                            null, new RegistrationCallback() {
                                @Override
                                public void onRegister(Registration registration, Exception e) {

                                }
                            });
```

**Comment by deneha** [comment]
@davidwrede Could you please assist?  If you can, please update on status of this issue.

**Comment by RickSaling** [comment]
With SDK 2.0+ we use the AsyncTask, not the callback (and I have repeatedly tested this code).
If you are still having problems, make sure you are using SDK 2.0 (you should have this line in the dependencies section of your gradle file:
    compile files('libs/mobileservices-2.0.1-beta.jar')

Please compare your code with the updated current tutorial, it has this code:

@Override
public void onRegistered(Context context,  final String gcmRegistrationId) {
    super.onRegistered(context, gcmRegistrationId);

    new AsyncTask<Void, Void, Void>() {

        protected Void doInBackground(Void... params) {
            try {
                ToDoActivity.mClient.getPush().register(gcmRegistrationId, null);
                return null;
            }
            catch(Exception e) { 
                // handle error             
            }
            return null;            
        }
    }.execute();
}

**Comment by deneha** [comment]
@boolship We think the issue has been resolved. If the issue persists, please comment and we'll reopen this issue.
