### ISSUE TITLE
Use case: node-pre-gyp documentation

### ISSUE THREAD

**Issue by jasonwilliams200OK** [Azure/azure-content#2432]
node.js and now even io.js are getting popular by day and new use cases are coming to the light. One of the fundamental use-case is C++ addons for node.js and io.js.

Please add clear documentation on how to use node-pre-gyp with Azure Storage. Related: https://github.com/mapbox/node-pre-gyp/issues/134.

node-pre-gyp is a supplementary tool for [node-gyp](https://github.com/TooTallNate/node-gyp/), which automates the process of building the C++ addons. The typical use-case is to build the binding using node-gyp on CI server (Travis for Mac and Linux, AppVeyor for Windows) and upload it to hosting server (in this case we are using Azure Storage), without needing to install build tool-chain on local machine. No doubt this seems like an improvised usage of CI server, but you will be amazed to find out how many popular node apps have adapted this approach due to its automated nature.

Since repositories on GitHub provide first-class-citizenship to Amazon services and Azure lacks out of the box support for many many such facilities, we expect Azure team to take initiative and make this process as pleasant as the one provisioned for Amazon.

**Comment by deneha** [comment]
@jimbe Sent mail to ask status.

**Comment by jimbe** [comment]
Hi Jason. Sorry for the delay in replying to your comment. We support the install command because storage is really just another HTTPS URI to access your blob(s). We will look into supporting node-pre-gyp and provide an alternative to S3 in the future. Thanks.
