### ISSUE TITLE
Data upload failure in Azure ML

### ISSUE THREAD

**Issue by Chinezeh** [Azure/azure-content#2473]
Pls guys, I am trying to upload a CSV file and this is what I am getting. Pls, any help? 

Thank you.

Dataset upload failed. Internal Service Error. Request ID: b043ceae-5516-48f4-be11-3be51acb7543 2015-01-28 15:48:07Z

**Comment by garyericson** [comment]
This would be an excellent question to raise at the Machine Learning Forum (https://social.msdn.microsoft.com/forums/azure/en-US/home?forum=MachineLearning). There are a number of experts there who can probably help you with a specific issue like this.

**Comment by Chinezeh** [comment]
Thank you garyericson
