### ISSUE TITLE
Custom event property name is not displayed

### ISSUE THREAD

**Issue by Tonven** [Azure/azure-content#2529]
In [this](https://github.com/Azure/azure-content/blob/master/articles/app-insights-search-diagnostic-logs.md#run-your-app-and-view-the-results) article you have an example of custom event property "Difficulty" - hard. When I send custom event to azure, names of events are not displayed. Instead I see the following:"context.custom.dimensions.0.value". The same goes for metrics:"context.custom.metrics.4.value". But the names are sent, because if I will search them, they will appear. The values are displayed correctly.

**Comment by gardnerjr** [comment]
Those should now be appearing correctly since a deployment yesterday (2/4/2015).

**Comment by Tonven** [comment]
For me it showed correctly only for 2 days. Now it works only for traces. Doesn't work neither for events , neither for exceptions,   Currenty it look like this for events: 
![capture](https://cloud.githubusercontent.com/assets/2392980/6184619/9d87ac62-b364-11e4-8f50-6347ff2a0868.PNG)

**Comment by gardnerjr** [comment]
Those are custom metrics, which we have an existing bug for in event details and the team that owns that is working on it.  Metrics will correctly display in metrics explorer, though.

Sent from my Windows Phone
________________________________
