### ISSUE TITLE
Markdown syntax for headings (h1..6/#...######)

### ISSUE THREAD

**Issue by codespare** [Azure/azure-content#2566]
Many, but not all, articles use:
#Heading 1
##Heading 2
...etc
to markup headings, without space between # and the heading text.
Could you use:
# Heading1
## Heading2
...
?
The missing space causes some markdown processors, notably those from the CommonMark family, to treat those heading as paragraph and keep the # prefix.
A mass regex replace of:
^(#+)([^#\s].+)$
with
${1} ${2}
does the trick from what I can tell.

**Comment by tysonn** [comment]
Thanks for taking the time to make a suggestion. With markdown, there's many ways to arrive at the same end, and so we have chosen to use the guidance offered by GitHub for markdown as our standard. The GitHub markdown help specifies the pound sign method: https://help.github.com/articles/markdown-basics/.

**Comment by codespare** [comment]
Well yes, that's the point I am trying to make: If you look at the section on headings in the github help link you shared, there is a space between the # and the first letter of the heading. A few hundreds of the articles in the repository omit that space, e.g. use #Heading instead of # Heading. You can actually see the difference I my initial message: The #heading without space are not rendered properly by github.

-----Original Message-----
