### ISSUE TITLE
Broken Link to Storage End-To-End Troubleshooting

### ISSUE THREAD

**Issue by MattAllison** [Azure/azure-content#2572]
The link to http://azure.microsoft.com/en-us/documentation/articles/articles/storage-e2e-troubleshooting/ is a broken link. 

The current link points to http://azure.microsoft.com/en-us/documentation/articles/articles/storage-e2e-troubleshooting/ and the proper link would be http://azure.microsoft.com/en-us/documentation/articles/storage-e2e-troubleshooting/.

In short, there's an extra /articles in the URL.

**Comment by tysonn** [comment]
What was the page you were on?

**Comment by MattAllison** [comment]
Apologies for not including that - new to Github and I assumed the comment would track the page I was on.  The article is http://azure.microsoft.com/en-us/documentation/articles/storage-monitoring-diagnosing-troubleshooting/.
