### ISSUE TITLE
missing directory in example for the Suse

### ISSUE THREAD

**Issue by gwojdyla** [Azure/azure-content#2934]
The following line doesn't contain /datadrive
`/dev/disk/by-uuid/33333333-3b3b-3c3c-3d3d-3e3e3e3e3e3e   /   ext3   defaults   1   2`

**Comment by deneha** [comment]
@gwojdyla Thank you for the suggestion. We would like to invite you to contribute to the article that you think should be changed through the GitHub functionality to collaborate directly with the other authors of the article.
