### ISSUE TITLE
Why Some codes are still hosted via CodePlext

### ISSUE THREAD

**Issue by krishnazure** [Azure/azure-content#3137]
I forked the Azure-Content. But some of the codes still live in CodePlex. Why cant everything be hosted in GitHub. IT will be very productive to do that..

**Comment by deneha** [comment]
@krishnazure Thank you for the suggestion.  We would like to invite you to contribute to the article that you think should be changed through the GitHub functionality.  If that does not seem like an option, please give us some more information on your suggestion so we can help you better.
