### ISSUE TITLE
Docker client installation instructions

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-content#3328]
@squillace, here:
http://azure.microsoft.com/en-us/documentation/articles/virtual-machines-docker-with-xplat-cli/

> Follow the Docker installation instructions to install Docker locally on your computer. For most operating systems and distributions, this means typing `apt-get install docker.io`. Confirm that the Docker version is at 1.0 or greater.

`docker.io` package is not maintained by Docker and usually falls behind newer versions.

We must suggest users to follow the commands here https://docs.docker.com/installation/ubuntulinux/

**Comment by deneha** [comment]
@ahmetalpbalkan Thank you for the suggestion.  Since you are a MSFT employee, we ask that you use the GitHub capability to contribute to the article by submitting a change and a pull request through the process.  If you need guidance on how this works, please see the contributors guide here: https://github.com/Azure/azure-content-pr/blob/master/contributor-guide/contributor-guide-index.md

**Comment by ahmetalpbalkan** [comment]
@squillace can do better than I can, English is not really my native language. :-)

**Comment by deneha** [comment]
@squillace Can you please assist on this issue?  Looks like @ahmetalpbalkan has deferred to you on this one.

**Comment by squillace** [comment]
Hey cats--just landed. @ahmetalpbalkan @dehena ill get to this today or tomorrow morning.

**Comment by squillace** [comment]
Reviewing this now. Seems that docker has changed their tunes about docker.io, which was previously precisely their description about how to get the client on Ubuntu (as there used to be a debian package called, precisely "docker" so they had to call out the docker.io part). Now it might read:

>>>
Follow the Docker installation instructions to install Docker locally on your computer. 
>>>

and I'll just remove the part about docker.io -- as docker has documented that. Note, however, that debian *still* has the docker.io requirement. :-) https://docs.docker.com/installation/debian/

**Comment by ahmetalpbalkan** [comment]
@squillace the general installation command `curl https://get.docker.com | sh ` just works fine on debian too.

If users want to use `docker.io` pkg they must add `jessie-backports` apt repo to their debian setup (as documented). It might be smart to just redirect users to the docs.docker.com for that.

**Comment by squillace** [comment]
@ahmetalpbalkan back from vacation; time to fix this.

**Comment by squillace** [comment]
fixed. email offline.

**Comment by deneha** [comment]
@ahmetalpbalkan Thanks again for raising the issue.  The issue appears resolved now.  Please comment if the issue remains a problem and we'll reopen this issue.
