### ISSUE TITLE
Update LoginAsync method with new MobileServiceClient code

### ISSUE THREAD

**Issue by WiteCastle** [Azure/azure-content#3411]
The new MobileServiceClient code requires a JObject token when using the LoginAsync method. The documentation does not have this included. Can it be updated with the new login method? (Line 23 of mobile-services-windows-universal-dotnet-authenticate-app.md)

**Comment by WiteCastle** [comment]
I feel like this article shows how to grab the authentication token needed: http://visualstudiomagazine.com/Articles/2014/10/01/Add-Azure-Active-Directory-Support.aspx?Page=1

**Comment by deneha** [comment]
@WiteCastle  Thank you for the suggestion. We would like to invite you to contribute to the article that you think should be changed through the GitHub functionality. If that does not seem like an option, please give us some more information on your suggestion so we can help you better.

**Comment by ggailey777** [comment]
The LoginAsync method overload that takes a JObject token is only used when you are doing client-directed authentication using the Facebook SDK and have already gotten an authentication token from Facebook. This overload of LoginAsync() is used in a service-directed authentication tutorial where the service handles all of the token stuff, you just need to specify the provider.
