### ISSUE TITLE
choose-web-site-cloud-service-vm.md - does website comply with PCI?

### ISSUE THREAD

**Issue by idofl** [Azure/azure-content#3433]
From what I understand websites are not PCI compliant, as they enable FTP access to the deployment.

**Comment by deneha** [comment]
@tdykstra Could you please assist?

**Comment by tdykstra** [comment]
Azure App Service is PCI compliant.

**Comment by idofl** [comment]
I'm looking at http://azure.microsoft.com/en-us/support/trust-center/services/ and Azure Websites / WebApps is not there.
Is there some announcement that websites is PCI compliant?

**Comment by deneha** [comment]
@tdykstra Could you please help with this question?  Thank you.

**Comment by deneha** [comment]
@idofl Your request has been forwarded to the product team by @tdykstra.  Thank you very much for your input.  We're closing this issue now.  If you need further assistance, please feel free to open another issue.

**Comment by tdykstra** [comment]
The trust center page has been updated.
https://azure.microsoft.com/en-us/support/trust-center/services/
Thanks for bringing this to our attention.
