### ISSUE TITLE
PG::ConnectionBad: FATAL:  password authentication failed for user

### ISSUE THREAD

**Issue by MisinformedDNA** [Azure/azure-content#3438]
I followed the guide as closely as possible. The only difference I can think of is that I'm using Capistrano 3.4 and Ruby 2.0.0p451.

```
DEBUG [48968742]        rake aborted!
DEBUG [48968742]        PG::ConnectionBad: FATAL:  password authentication failed for user "Spree_production"
DEBUG [48968742]        FATAL:  password authentication failed for user "Spree_production"
```

**Comment by deneha** [comment]
@MisinformedDNA Thank you for this question.  Was there a page in documentation that you were using for this task you're describing?  If so, could you please include that so I can direct you to a subject matter expert?

**Comment by squillace** [comment]
@MisinformedDNA Hey Dan -- what document were you following here? I don't recognize the error at all..... help! :-)

**Comment by MisinformedDNA** [comment]
https://github.com/Azure/azure-content/blob/master/articles/virtual-machines-ruby-deploy-capistrano-host-nginx-unicorn.md

**Comment by tysonn** [comment]
Thanks for letting us know the article. I'm following up internally.

**Comment by devigned** [comment]
The database login / password combination is incorrect for spree_production. 

The bottom line is that the symlinked config/database.yml file on the box contains incorrect login / password data for the database. You should cat the file and determine if you can login to your database with the creds in that file.

**Comment by deneha** [comment]
@MisinformedDNA Has your question been answered?  We'll leave this issue open another week in case you still need assistance.

**Comment by MisinformedDNA** [comment]
I don't have time to verify as I've moved onto another service for this feature. I don't see how the credentials could have been wrong as I followed them step by step and I'm almost sure I verified the creds, but I'll have to look at it again, sometime later when I have more time.
