### ISSUE TITLE
Error compiling SendGrid code sample

### ISSUE THREAD

**Issue by varunchhabra** [Azure/azure-content#3549]
Hi,
I found an error in the documentation for developing a Web App on Azure using WebMatrix (http://azure.microsoft.com/en-us/documentation/articles/web-sites-dotnet-using-webmatrix/), and wanted to bring it to your attention.

In bullet 6 of the "Setup Mail" section, the instructions reference a SendGrid call "Deliver". When I try to run the app with this code, I get a compile error in IE referencing the unknown function Deliver. 

![web_app_error](https://cloud.githubusercontent.com/assets/9753325/7622377/f132b34c-f983-11e4-995a-7c6571d72e0d.JPG)

Looking through the SendGrid Nuget documentation, I found a function called "DeliverAsync". When I replaced the Deliver with DeliverAsync (line 85 in screenshot below),  

![web_app_error_2](https://cloud.githubusercontent.com/assets/9753325/7622441/5b04560e-f984-11e4-9e39-fcd7ba8cb00c.JPG)

the code compiles on the browser, and the emails get sent correctly.

**Comment by deneha** [comment]
@tfitzmac Tom could you please help with this issue?

**Comment by tfitzmac** [comment]
Yes, I'll take a look.

**Comment by tfitzmac** [comment]
I made the suggested change and tested it. Everything works. Fix is in https://github.com/Azure/azure-content-pr/pull/10932

**Comment by deneha** [comment]
@varunchhabra Thank you for your contribution!  The author has made your suggested change.  Please let us know if this solves the issue.

**Comment by varunchhabra** [comment]
Thanks folks for the prompt attention - the changes work.

**Comment by deneha** [comment]
@varunchhabra Great!  Thanks for letting us know.  I'll close this issue.  Please let us know if you need any further assistance.
