### ISSUE TITLE
Elastic Database Client Library doesn't show up

### ISSUE THREAD

**Issue by SilviaDoomra** [Azure/azure-content#3559]
When I search for keywords "Elastic" or "Elastic Database", Elastic Database Client library doesn't show up. Only Elastic Database Split-Merge Service shows up.

**Comment by deneha** [comment]
@jeffgoll Jeff, could you please follow up with Silvia on this issue?

**Comment by jeffgoll** [comment]
Hi Silvia, can you elaborate on which Search you were using? Was this azure.com search? And were you looking for the reference content?

**Comment by SilviaDoomra** [comment]
Hi Jeff,

Please feel free to ignore this. I found the root cause. I was looking in Universal apps – where it shouldn’t show up.

Thanks,
Silvia Doomra | Program Manager II | Azure SQL Database | Microsoft Corporation
