### ISSUE TITLE
overlapping documentation

### ISSUE THREAD

**Issue by yamatoya** [Azure/azure-content#3575]
The follow URLs is same documents.
But, 'sql-database-service-tier-advisor.md' is updated by #3574 

https://github.com/Azure/azure-content/blob/master/articles/sql-database-service-tier-advisor.md
https://github.com/Azure/azure-content/blob/master/articles/sql-database-pricing-tier-recommendations.md

**Comment by deneha** [comment]
@stevestein Could you please assist?

**Comment by stevestein** [comment]
Duplicate article (https://github.com/Azure/azure-content/blob/master/articles/sql-database-pricing-tier-recommendations.md) has been removed. Redirect has been requested.

**Comment by deneha** [comment]
@yamatoya We're closing this issue as resolved. Please let us know if you need any further assistance by leaving a comment to reopen the issue.
