### ISSUE TITLE
Java examples in service-bus-event-hubs-get-started-send-java.md are wrong

### ISSUE THREAD

**Issue by aidanmorgan** [Azure/azure-content#3582]
There are several issues with the java examples on this page.

1. The version of Qpid JMS AMQP available is 0.1.0 not 1.0
2. org.apache.qpid.amqp_1_0.jms.jndi.PropertiesFileInitialContextFactory does not exist in the packages referenced
3. The connection string needs a port added to it (5671)
4. URL Encoding of the password behaves differently than expected from the example code/instructions

At the moment I can't get a basic sending to Event Hub using Java working following this example. I suspect that there may have been some changes to the Qpid library since this was published.

**Comment by deneha** [comment]
@aidanmorgan Thanks for raising the issue!

@sethmanheim Could you please assist?

**Comment by sethmanheim** [comment]
Please ask the article author to take a look.

**Comment by sethmanheim** [comment]
@fsautomata Elio, can you please comment?

**Comment by aidanmorgan** [comment]
Thanks guys - am looking forward to getting this part working. It's the missing piece of a pretty cool demo I am setting up.

**Comment by fsautomata** [comment]
Hi Aidan,

It seems you are not including the JAR geronimo-jms_1.1_spec-1.1.1.jar which is part of that package and provides a lot of the JMS support which is not specific to Qpid.

We will update the tutorial ASAP.

Elio

**Comment by sethmanheim** [comment]
@aidanmorgan Does this resolve your issue?

**Comment by aidanmorgan** [comment]
I managed to resolve my issue by downloading an older version of QPID that has the missing classes. The correct version is here: 

http://www.apache.org/dyn/closer.cgi/qpid/0.32/binaries/qpid-amqp-1-0-client-jms-0.32-bin.tar.gz

**Comment by deneha** [comment]
@aidanmorgan The issue appears to have been corrected. We're closing this issue. Please comment if you need the issue to be reopened for any reason.  We'll be happy to assist if you need any further assistance.
