### ISSUE TITLE
SQL Azure Automated Export limit of 10 not documented

### ISSUE THREAD

**Issue by calebdoise** [Azure/azure-content#3634]
The following page:
https://github.com/Azure/azure-content/blob/master/articles/azure-subscription-service-limits.md

hosted here:
http://azure.microsoft.com/en-us/documentation/articles/azure-subscription-service-limits/

does not document that there is a limit of 10 (that's the default and maximum limit per subscription) for SQL Azure Automated Exports.

As indicated on this feedback item, a number of other people have stumbled blindly upon this limit:
http://feedback.azure.com/forums/231545-diagnostics-and-monitoring/suggestions/5181984-don-t-limit-the-number-of-automated-database-export

**Comment by deneha** [comment]
@calebdoise Thanks for raising the issue!

@rothja Could you please assist?

**Comment by rothja** [comment]
For SQL Database limits, we are pointing to another page. However, I see this is a subscription level limit and it might apply here. Please let me look into the best place to put this limit and I will make sure it is called out. Thank you.

**Comment by deneha** [comment]
@calebdoise Has your question been answered?  We'll leave this issue open for another week in case you need any further assistance.

**Comment by calebdoise** [comment]
I'm afraid it has not been answered. I don't see the limit of 10 automated database exports documented on any of the SQL pages to which this article links (if it's there, I can't find it). Aside from documenting that on the referenced page, it would also be helpful if that were to be displayed on the actual Azure portal page where people can configure automated database exports. I was told by customer service that there is absolutely no way for them to raise the limit above 10 per subscription since the feature is still in preview. However, the automated exports feature has been in preview for a *very* long time which makes me wonder if it will even be supported going forwards, especially since the customer service rep tried to tell me that I should use Point-In-Time-Restore (PITR) on the new Azure database tiers. I have used PITR where it applies, but PITR is not a substitute for periodic backups that can be archived indefinitely.

**Comment by rothja** [comment]
I apologize for the delay. I am still investigating whether this should go onto the main limits page or just the other pages. However, at the very least, we can get this put onto the other pages that talk about automatic database export. I will target updating those at least by the end of the week. As for the limits page, we do not document (yet) a lot of SQL specific limits. If we get a table in place for the SQL limits here, I'll makes sure this is included. I'll update this request by the end of the week.

**Comment by rothja** [comment]
I have product team today to confirm the limit still exists, and then I will get into the docs. My response on this is unacceptably slow, and I apologize. Thanks.

**Comment by rothja** [comment]
Added this to the resource limits topic, https://azure.microsoft.com/en-us/documentation/articles/sql-database-resource-limits/, and it should show up later today when published. Thank you.

**Comment by tysonn** [comment]
@calebdoise - Jason updated the topic to address this issue, so closing. Thanks for raising it.
