### ISSUE TITLE
Use Component.Verson instead of Properties["AppVersion"] in documentation

### ISSUE THREAD

**Issue by SergKanz** [Azure/azure-content#3724]
@alancameronwills, some people got confused by example on the page:
https://azure.microsoft.com/en-us/documentation/articles/app-insights-api-custom-events-metrics/

Specifically instead of setting Properties["AppVersion"] it is better to set Component.Version as this property is used in UI as "Application Version".

**Comment by alancameronwills** [comment]
OK, thanks!

**Comment by jimbe** [comment]
Alan updated the file.
