### ISSUE TITLE
http://azure.microsoft.com/en-us/documentation/articles/feed/ error

### ISSUE THREAD

**Issue by damnan** [Azure/azure-content#3730]
Hello,
The [documentation updates feed](http://azure.microsoft.com/en-us/documentation/articles/feed/) on Azure Web site is in error because of the 'Deploying Password Management and training users to use it' article contains an unescaped '&' character in its description field.

**Comment by tysonn** [comment]
Thank you for calling this out - an update has been made and accepted.
