### ISSUE TITLE
Azure AD Connect Download link is not working (not found)

### ISSUE THREAD

**Issue by jshuot** [Azure/azure-content#3751]
The URL is not working properly for the following link (Azure AD Connect) : http://go.microsoft.com/fwlink/?LinkID=615771

We are sorry, the page you requested cannot be found. 

The URL may be misspelled or the page you're looking for is no longer available.

**Comment by deneha** [comment]
@jshuot Thanks for letting us know! I'm going to pass this onto the author.  Could you please indicate which page you found this link on?

**Comment by deneha** [comment]
@jshuot Thanks for letting us know!  I just tried to download the materials at that link and it worked for me.  Could you please retry and let me know your steps if it doesn't work for you?

**Comment by billmath** [comment]
Dene, this has been fixed.  The download was put up before the official GA announcement.  Then they moved the date out so it was taken down.  It should be working now.  Thanks!

**Comment by tysonn** [comment]
@jshuot - This should be resolved now, thanks for the report.
