### ISSUE TITLE
the links in the documentation return 404

### ISSUE THREAD

**Issue by rostandk** [Azure/azure-content#3776]
The links in following documentation are returning a 404 page not found errors.

https://azure.microsoft.com/en-us/documentation/articles/stream-analytics-key-concepts/

**Comment by deneha** [comment]
@rostandk Thanks for raising this issue!  I've checked the links at the page and the issue appears to have resolved itself.  Would you let us know if the issue persists for you?

**Comment by deneha** [comment]
@rostandk We think the issue has been resolved.  If the issue persists, please comment and we'll reopen this issue.
