### ISSUE TITLE
Spray.io

### ISSUE THREAD

**Issue by omidb** [Azure/azure-content#3805]
Hi,

How can I deploy my web app using spray.io? it's using Scala and Sbt.

Thanks

**Comment by deneha** [comment]
Thanks for your question!  I'll try to find someone who can answer your question.

**Comment by tysonn** [comment]
@omidb Hi Omid, thanks for filing this issue. We’re happy to respond to issues that are directly related to documentation feedback in this repo. I think this question goes beyond that scope, so I'm going to close the issue. StackOverflow might be a good place to ask this question.
