### ISSUE TITLE
key-vault-use-from-web-application.md missing information

### ISSUE THREAD

**Issue by jameskeongchen** [Azure/azure-content#3944]
In the Retrieve the secret on Application Start the code line:
var kv = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(Utils.GetToken));

doesn't make sense?

there is no explanation of how to pass in the authority and resource and scope in the Task?
GetToken(string authority, string resource, string scope)

please help ask the KeyVault team to update this so the walkthrough is a little clearer..

**Comment by deneha** [comment]
@jameskeongchen Thanks for raising this issue!  I'll notify the author of your request.

**Comment by adhurwit** [comment]
@jameskeongchen I appreciate the comment, but the code is correct. GetToken is supplied as a Callback function so you are not calling it directly. I have a sample project in a repo in github for this. I hope this helps.

**Comment by jameskeongchen** [comment]
thanks - sorry it just want making sense to me - we can close this issue out; ill keep at it - if you have a link to that repo that would be swell! thanks again!

**Comment by adhurwit** [comment]
Here's the repo - https://github.com/adhurwit/AzureTutorials
the project you want is KeyVaultUseFromWebApp

**Comment by jameskeongchen** [comment]
forked!
