### ISSUE TITLE
Article title not capitalized 

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-content#3947]
`azure-content/articles/virtual-machines/virtual-machines-linux-diagnostic-extension.md`

Look at page `<title>` tag. https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-diagnostic-extension/ doesn't look good in search results.

**Comment by deneha** [comment]
@ahmetalpbalkan  Thanks for calling this out.  We’ll push this article through the copy edit process.

**Comment by ahmetalpbalkan** [comment]
@deneha I don't think this is fixed either in internal or external repo yet. Why closed?

**Comment by deneha** [comment]
@ahmetalpbalkan Sorry, Ahmet for any confusion.  This has been put into the copy-edit queue.  I can leave this issue open until that is done if you'd like.

**Comment by ahmetalpbalkan** [comment]
That's probably what any issue reporter would like to see. :-) Also keeping it open helps if items get lost in the queue and if you close only when the fix is in, you won't be taking chances. :-)

**Comment by squillace** [comment]
:+1:

**Comment by deneha** [comment]
@ahmetalpbalkan I've fixed the issue for the page title.  Please comment if this does not resolve your issue.
