### ISSUE TITLE
Optimistic concurrency control with etag for all operations?

### ISSUE THREAD

**Issue by toriumi0118** [Azure/azure-content#3960]
I'm creating new web application, with azure table storage.

When I used InsertOrReplace operation, the optimistic lock never worked.
I googled it and I found [this blog](http://azure.microsoft.com/blog/2014/09/08/managing-concurrency-in-microsoft-azure-storage-2/).

Is it same behavior with latest version? If so could you please write about it in the article.
thanks.

**Comment by tamram** [comment]
Hi, can you provide us with more information about the problem you're having?

The behavior is the same with the latest version. See the storage documentation for the most up-to-date version of the optimistic concurrency article (but it is very similar to the blog post at this time).

https://azure.microsoft.com/en-us/documentation/articles/storage-concurrency/

**Comment by toriumi0118** [comment]
@tamram 
Thanks your replay.
I had not read the document that you posted.

I did misreading, sorry.
I thought InsertOrReplace also have concurrency control same as others(like update query) when I read first article below.
[https://azure.microsoft.com/en-us/documentation/articles/storage-nodejs-how-to-use-table-storage/](https://azure.microsoft.com/en-us/documentation/articles/storage-nodejs-how-to-use-table-storage/)

The 'Update an entity section' refers about etag for concurrency control, but it looks like work for both  query(Update and also InsertOrReplace).

My problem is solved, thanks!!

**Comment by deneha** [comment]
@toriumi0118 Thanks for letting us know the answer solved your issue.  I'm going to close this issue now - please feel free to comment if it needs to be reopened.
