### ISSUE TITLE
Please update the content in cloud-services-continuous-delivery-use-vso-git with examples for web apps NOT created in Visual Studio

### ISSUE THREAD

**Issue by matiaslarsson** [Azure/azure-content#3965]
It would be great if you could demonstrate how to set up continuous delivery from vso git when the project is a plain node.js project (created using Visual Studio Code or some other third party text editor).

In these cases there will be no *.sln file in these cases so using the Azure Website build definition template will fail since it includes a Build step requiring a *.sln project file.

Removing the build step (since we only need the files copied) will fail since the Azure Web Site Deployment step requires a *.zip file so I assume one has to use a PowerShell script (or something similar) to zip the directory the "Get sources" build step drops files in?

https://azure.microsoft.com/en-us/documentation/articles/cloud-services-continuous-delivery-use-vso-git/

**Comment by deneha** [comment]
@matiaslarsson Thanks for raising this issue!  I've assigned a member of our team to review your question.

**Comment by kempb** [comment]
Hi @matiaslarsson, I'm not really sure about this, but I'll investigate and let you know what I come up with.

**Comment by matiaslarsson** [comment]
Thanks @kempb!

**Comment by kempb** [comment]
Hi again @matiaslarsson, sorry for the delay answering; I was consulting with various experts here about the issue. Unfortunately, continuous deployment support for a non-.net project hosted on VSO to an Azure Web App isn't really supported at the moment. However, Jason Poon will be following up with you to possibly provide a workaround. He authored this topic: http://www.jasonpoon.ca/2015/07/07/azure-web-app-continuous-integration/  I hope this helps!  Regards, Kemp.

**Comment by jpoon** [comment]
Hey @matiaslarsson!

The issue has been raised with the engineering team. Feel free to also add this to uservoice (https://visualstudio.uservoice.com/forums/121579-visual-studio/category/30925-team-foundation-server-visual-studio-online). In the meantime, as @kempb was mentioning, the workaround I came up with (as detailed in that blog post) breaks down to:

1. Setup local Git repository on the Azure Web App
2. Modify the build definition (which you can get from the blog post) to push to above Git repository\

Hope that helps.

**Comment by jpoon** [comment]
Hey @matiaslarsson!

The issue has been raised with the engineering team. Feel free to also add this to uservoice (https://visualstudio.uservoice.com/forums/121579-visual-studio/category/30925-team-foundation-server-visual-studio-online). In the meantime, as @kempb was mentioning, the workaround I came up with (as detailed in that blog post) breaks down to:

1. Setup local Git repository on the Azure Web App
2. Modify the build definition (which you can get from the blog post) to push to above Git repository\

Hope that helps.

**Comment by DarqueWarrior** [comment]
I think this does what you want.
https://azure.microsoft.com/en-us/documentation/articles/web-sites-nodejs-develop-deploy-mac/

**Comment by matiaslarsson** [comment]
Thanks everyone, I'll try your suggestions next week and get back to you with a thumbs up or thumbs down.

Also, I'll probably start a uservoice ticket for a smoother continuous deployment support for a non-.net project hosted on VSO to an Azure Web App experience if nobody else already has submitted a request.

**Comment by matiaslarsson** [comment]
@jpoon I might be missing something but it seems your workaround still requires a Visual Studio solution file for the VSO build to succeed? Since I'm using Visual Studio Code and node.js, there is no solution file so I just entered `/` under 2.1 (Relative path to the solution/project file you want to build) which of course failed.

```
Cannot locate a solution file.
Exception Message: The project file 'C:\a\src' was not found. (type FileNotFoundException)
Exception Stack Trace: at System.Activities.Statements.Throw.Execute(CodeActivityContext context)
at System.Activities.CodeActivity.InternalExecute(ActivityInstance instance, ActivityExecutor executor, BookmarkManager bookmarkManager)
at System.Activities.Runtime.ActivityExecutor.ExecuteActivityWorkItem.ExecuteBody(ActivityExecutor executor, BookmarkManager bookmarkManager, Location resultLocation)
TF270003: Failed to copy. Ensure the source directory C:\a\bin exists and that you have the appropriate permissions.
```

**Comment by matiaslarsson** [comment]
@DarqueWarrior Yes, the result from that article is what I want but I was looking for a way to have Continuous Integration from Visual Studio Online GIT publish to an Azure Web App (without a VS .sln-file). It looks like the article you reference is doing it straight from a local GIT to the Azure Web App.

Maybe VSO Build is coupled so tightly to the VS development environment that what I'm trying is impossible right now.

It doesn't feel like it should be so hard to copy some files though. ;)

**Comment by jpoon** [comment]
@matiaslarsson, ah, you are totally right. Here's a new version removing stripping all the non-relevant build steps and leaving the `git push remote azure` bit: 

https://gist.github.com/jpoon/736ee1ed79ea768c0799

 Disclaimer, I haven't tested this myself :)

**Comment by matiaslarsson** [comment]
@jpoon Thanks, will try!

**Comment by matiaslarsson** [comment]
@jpoon Worked like a charm! Now I just have to figure out how to get a Gulp build step in there somewhere. Are you using Kudu to edit the deployment templates?

It would be nice not to have to go through all these hoops in the future though, just because I run Visual Studio Code and deploying non .sln projects so I'll keep my fingers crossed for a more permanent solution.

**Comment by jpoon** [comment]
Re: More permanent solution. They are working on it ;)

You can most definition edit Kudu to add your build step. 
```
> npm install azure-cli --global
> azure site deploymentscript --node
```
That'll generate the default build scripts (`deploy.sh` or `deploy.cmd`) that you can modify to add whatever you need to do.

**Comment by kempb** [comment]
Hi, @matiaslarsson - if there's anything other issues with this topic I can help with, please let me know. Otherwise, if you would close this issue, I'd appreciate it.  :)   (You can always open a new one if needed.)

**Comment by mwmoeller** [comment]
Thanks @jpoon  - this looks super helpful!  I'm having a slight issue with the build though.  When I create a build definition that uses this template, I get the following error. What am I doing wrong?

Exception Message: The directory name is invalid (type Win32Exception)
Exception Stack Trace: 
Server stack trace: 
at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
at Microsoft.TeamFoundation.Build.Workflow.Activities.InvokeProcess.ProcessWrapper.Start()
at Microsoft.TeamFoundation.Build.Workflow.Activities.InvokeProcess.InvokeProcessInternal.RunCommand(AsyncState state)
at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
at System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage(IMessage msg, IMessageSink replySink)
Exception rethrown at [0]: 
at System.Runtime.Remoting.Proxies.RealProxy.EndInvokeHelper(Message reqMsg, Boolean bProxyCase)
at System.Func`2.EndInvoke(IAsyncResult result)
at System.Activities.AsyncCodeActivity`1.System.Activities.IAsyncCodeActivity.FinishExecution(AsyncCodeActivityContext context, IAsyncResult result)
at System.Activities.AsyncCodeActivity.CompleteAsyncCodeActivityData.CompleteAsyncCodeActivityWorkItem.Execute(ActivityExecutor executor, BookmarkManager bookmarkManager)
TF270003: Failed to copy. Ensure the source directory d:\a\bin exists and that you have the appropriate permissions

**Comment by mwmoeller** [comment]
So once I changed the working directory on lines 63 and 81 to "d:\a\src" it worked.  The only issue I'm seeing now is that it is deploying out of origin/master rather than origin/develop as set up in the "source settings" of the build definition.  Any thoughts on that?  I tried editing the template to do 'git push azure develop:refs/heads/master' - but got an error indicating that develop doesn't exist even though it does.  

This could totally fix our workflow if we can get building out of develop.  Any thoughts?  Thank you!

**Comment by matiaslarsson** [comment]
OK, let's close this one... even though the ~~solution~~ workaround is in this thread and not in the Azure documentation. ;)

**Comment by matiaslarsson** [comment]
It seems your colleague Thiago Almeida has written a blog post detailing the steps necessary for deploying a plain node project from VSO (VSTS) to an Azure web app. It works great! Check out http://www.talmeida.net/blog/2015/10/26/infrastructure-as-code-and-continuous-deployment-of-a-nodejs-azure-documentdb-solution

(I skipped the Infrastructure as Code-part and went straight for the npm and gulp build steps.)
