### ISSUE TITLE
IPython Notebook Inline Config Not Handled Properly 

### ISSUE THREAD

**Issue by Ricky-N** [Azure/azure-content#3996]
for the ipython notebook demo: 
https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-python-ipython-notebook/#a-powerful-paradigm-live-computational-documents-with-rich-media

the matplotlib / pylab inline setting is no longer supported in ipython_notebook_config.py, should be moved into ipython_config.py (or kernel config) for python 3. See this q&a:
http://stackoverflow.com/questions/28964353/ipython3-automatically-config-matplotlib-inline

FYI, followed instructions for Linux VM:

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty

**Comment by deneha** [comment]
@Ricky-N Thanks for raising the issue!  I've notified the author to review your request.

**Comment by deneha** [comment]
@huguesv Would you please assist?

**Comment by crwilcox** [comment]
https://github.com/Azure/azure-content/pull/4674

**Comment by tysonn** [comment]
@Ricky-N - It looks like @crwilcox made updates to reflect this, so I'm closing the issue.
