### ISSUE TITLE
export appinsight to azure table using stream-analytics

### ISSUE THREAD

**Issue by riccardo91** [Azure/azure-content#4008]
i've succesfully followed the tutorial to export stats from blob storage to sql database. Due the amount of data i would like to move data to azure tables.
Unfortunately the the stram process seems to crash wit a generic error.
here my query

    SELECT A.context.data.eventTime as RowKey
    INTO pageviewstable
    FROM inputinsightblob A

do you have any recommendation? thank you!

**Comment by deneha** [comment]
Hi @riccardo91 - Thanks for filing this issue. We’re happy to respond to issues that are directly related to documentation feedback in this repo. I think this question goes beyond that scope, so I'm going to close the issue. StackOverflow might be a good place to ask this question.
