### ISSUE TITLE
Database project issue while publishing

### ISSUE THREAD

**Issue by rameshbolla** [Azure/azure-content#4025]
Hi,
I followed article https://azure.microsoft.com/en-in/documentation/articles/cloud-services-dotnet-continuous-delivery/ to publish my web roles to Azure. It was working fine.

Recently i have added a database project to solution, then build try to publish database project too. Keep failing the build.

I don't want build to publish database project, can build definition drop DACPAC file to given dropfolder location.

Could you suggest how to solve this issue ?

/Ramesh

**Comment by deneha** [comment]
Hi @rameshbolla , thanks for filing this issue. We’re happy to respond to issues that are directly related to documentation feedback in this repo. I think this question goes beyond that scope, so I'm going to close the issue. StackOverflow might be a good place to ask this question.
