### ISSUE TITLE
Update for CDN in limits topic

### ISSUE THREAD

**Issue by tysonn** [Azure/azure-content#4032]
@steved0x --- Sherry Toly from marketing was told that a quota that applies to the CDN service and that is not documented is a soft limit of 100. There's a request to add it to http://azure.microsoft.com/en-us/documentation/articles/azure-subscription-service-limits/ . Assigning to Steve as I believe he covers CDN.

**Comment by steved0x** [comment]
I don't work on CDN but I will find out who does.

**Comment by davidwrede** [comment]
@Juliako, can you work with the product team to get the CDN limits into the limits doc?

**Comment by Juliako** [comment]
The CDN limits section was added here: https://azure.microsoft.com/en-us/documentation/articles/azure-subscription-service-limits/#cdn-limits

**Comment by Juliako** [comment]
The issue has been resolved, please close it.
