### ISSUE TITLE
Not getting ProgressFilter() class

### ISSUE THREAD

**Issue by ShreyashPromact** [Azure/azure-content#4041]
Hello, 

I am new to implement Azure Mobile service to authenticate user. I have refer this readme file to understand and implement the azure user authenticate for mobile app.
https://github.com/Azure/azure-content/blob/master/includes/mobile-services-android-authenticate-app-refresh-token.md

And

https://azure.microsoft.com/en-in/documentation/articles/mobile-services-dotnet-backend-android-get-started-users/

In this code, there are two types of filter used during initializing the AzureMobileService client.

1. new ProgressFilter()
2. new RefreshTokenCacheFilter()

in below code:

 mClient = new MobileServiceClient(
                "https://<YOUR MOBILE SERVICE>.azure-mobile.net/",
                "<YOUR MOBILE SERVICE KEY>", this)
                   .withFilter(new ProgressFilter())
                   .withFilter(new RefreshTokenCacheFilter());

Here i am not getting class new ProgressFilter(). Even there is no good information available for that class.  Either I have not review it proper or the information is not updated properly.

Can anyone help me to give proper information for the class new ProgressFilter() used in authenticate user? or can anyone share the link for that information of that class?

Thanks.

**Comment by deneha** [comment]
@ShreyashPromact Thanks for raising the issue!  I'm looking for one of our team to review.

**Comment by soninaren** [comment]
@ShreyashPromact  have added the missing ProgressFilter class in the PR above.

**Comment by deneha** [comment]
@ShreyashPromact We've implemented your suggestion.  You should see the changes appear in the next 24 hours.

**Comment by ShreyashPromact** [comment]
@deneha @soninaren  

Thanks a lot.
I will wait for that update.

Sincerely,
Shreyash
