### ISSUE TITLE
AppInsights: Exceptions are counted twice in Azure AppInsights Dashboard

### ISSUE THREAD

**Issue by alecor191** [Azure/azure-content#4064]
Hi,

I'm struggling with the following: Whenever I log an exception and then look at the AppInsights dashboard in Azure, the exception is counted twice. I.e. if I log 1 exception I see 2 in the dashboard. If I log 5 I get 10 in the dashboard.
Interestingly when I further drill down to the exception details to see the list of exceptions, I see the correct number of exceptions I logged (see screenshot below).
I verified that I'm _not_ logging exceptions twice.

Here an example code snippet I used to repro the issue:

```csharp
try
{
    throw new OutOfMemoryException("My custom error");
}
catch (Exception e)
{
    _logger.LogError("An error occurred", e);
}
```

And here the screenshot of my dashboard after logging a single exception:

![appinsights_screenshot_exceptions](https://cloud.githubusercontent.com/assets/6270008/8823829/6474429e-3070-11e5-831b-6bd08d8080d6.png)

Am I doing anything wrong or is this an issue in the dashboard?

**Comment by deneha** [comment]
Hi @alecor191 , thanks for filing this issue. We’re happy to respond to issues that are directly related to documentation feedback in this repo. I think this question goes beyond that scope, so I'm going to close the issue. StackOverflow might be a good place to ask this question.
