### ISSUE TITLE
Upgrade and Installation examples for respective distros

### ISSUE THREAD

**Issue by kangman** [Azure/azure-content#4075]
I see that there is a recommended procedure stated in the README 

"Installation via your distribution's package repository is preferred."

It would be great to have some examples to illustrate for each distribution.  

e.g. sudo apt-get ...
sudo yum install ...

**Comment by deneha** [comment]
@kangman Thanks for the suggestion!  I'll pass it on to the person in charge of that page.

**Comment by tysonn** [comment]
@deneha - The quoted line is in articles/virtual-machines/virtual-machines-linux-agent-user-guide.md. 

@szarkos - Can you take a look at this?

**Comment by szarkos** [comment]
The process and package name varies between distros.  Typically you can just search the package repo for your distribution for keywords like "Azure".  For the distributions we support (CentOS, Oracle Linux, SLES, openSUSE and Ubuntu) we have the exact commands you can run in the various BYOL documents: https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-create-upload-vhd/.  See the links to the various distro-specific docs in Step 1.

**Comment by kangman** [comment]
@szarkos Thanks, is there documentation on testing the agents that the BYOL is indeed communicating with Azure?  This probably could also apply to legacy Azure VMs in production that needs the waagent to access new services e.g. recovery services IaaS backups.  
Adding the correct repos for each distro seems like a good troubleshooting step for the walinux agent documentation in general rather than have it deep linked within articles.

**Comment by timlt** [comment]
@squillace for fyi.  Base article is:
https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-create-upload-vhd/

**Comment by timlt** [comment]
@tysonn   Ok to close.
@kangman Thanks for the feedback, we've pointed to the correct doc information and sent the suggestion to our Linux Agent team to consider options for presenting the distro and repo info in an optimal way.
