### ISSUE TITLE
wget for version 2.1.0 gets 404

### ISSUE THREAD

**Issue by kangman** [Azure/azure-content#4076]
#wget https://raw.githubusercontent.com/Azure/WALinuxAgent/WALinuxAgent-2.1.0/waagent

```
--2015-07-23 15:55:24--  https://raw.githubusercontent.com/Azure/WALinuxAgent/WALinuxAgent-2.1.0/waagent
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.27.76.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.27.76.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-07-23 15:55:24 ERROR 404: Not Found.
```

**Comment by deneha** [comment]
@kangman Thanks for raising this issue!  What web page was this on?

**Comment by kangman** [comment]
https://github.com/Azure/azure-content/blob/9ecb25e737df830ec9ee8bb9e1b439518ac31392/articles/virtual-machines/virtual-machines-linux-update-agent.md

**Comment by deneha** [comment]
@kangman That appears to be an example link - this is a screenshot from the article
![image](https://cloud.githubusercontent.com/assets/11968312/8860590/b1b741a4-3139-11e5-9814-6a9bf8199d72.png)

**Comment by kangman** [comment]
@deneha  right they do state to fill in the version number of the agent you want to download. 
I wanted to get the latest version which is 2.1.0 and that does not seem to be available 

looking at the master branch shows the same examples to follow.  So if I wanted to get 2.1.0 is the URL different than shown in the example?

**Comment by deneha** [comment]
@kangman Thanks for pointing that out - I'll see if we can get the author to help.

**Comment by deneha** [comment]
@SuperScottz Would you please review this and provide feedback?

**Comment by SuperScottz** [comment]
Sorry for late, I 'm looking into it, we have some code structure change in 2.1.0 version of Agent, the download need be updated, I will get back the right steps soon.

**Comment by SuperScottz** [comment]
@kangman 
For the latest version of Azure Linux Agent 2.1.0, please use below steps to update:
1. Install pip or setuptools. Either of these should work.
•	pip https://pip.pypa.io/en/latest/installing.html
•	setuptools https://pypi.python.org/pypi/setuptools
2. Download agent code
•	wget https://github.com/Azure/WALinuxAgent/archive/WALinuxAgent-2.1.0.zip agent.zip
•	unzip agent.zip -d agent
3. Run
•	cd agent
•	python setup.py install
On the other hand, I'm updating my doc virtual-machines-linux-update-agent.md right now.

**Comment by kangman** [comment]
cool @SuperScottz , does this version also support legacy azure Linux vm's?

**Comment by SuperScottz** [comment]
@kangman , Yes, it support the legacy Linux VM in Azure, the major change we made is the to make the Linux Agent code more modularized, you could see the install file was divided into several files with more clear modules, and it will be easy to be customized or managed.

**Comment by SuperScottz** [comment]
@kangman we have updated the README for 2.1.0, see: https://github.com/Azure/WALinuxAgent/tree/2.1
and I have updated the ACOM doc you are referencing, it will be updated shortly in azure.com.
Thank you for your nice feedback to Linux Agent. :)

**Comment by kangman** [comment]
no thank you @SuperScottz   :+1:
