### ISSUE TITLE
mobile-services-how-to-use-server-scripts has incorrect link to .NET documentation

### ISSUE THREAD

**Issue by bateau** [Azure/azure-content#4081]
mobile-services-how-to-use-server-scripts has incorrect link to .NET documentation.  It points to mobile-services-dotnet-backend-how-to-use, which throws a 404.  It's broken on public Azure Docs website as well.

**Comment by deneha** [comment]
@bateau Thanks for raising this issue.  I'll notify the author.

@RickSaling Could you please assist?

**Comment by RickSaling** [comment]
Hey, thank you much for finding this and telling us!
Right now I am "heads down" on a new Android topic, so this will have to wait until I get a break/pause point, hopefully in the next day or two.
Thanks again!

**Comment by ggailey777** [comment]
I can't repro this issue. There is no link from the server scripts topic to any .NET topics, except the .NET SDK reference in the left-nav, and that link works.

**Comment by RickSaling** [comment]
I deleted the link: it was part of the switcher, and was pointing at a non-existent topic about .Net backend scripts (scripts don't exist in the .Net backend)

**Comment by deneha** [comment]
@bateau This issue appears resolved, so we're closing this issue.  If you need us to reopen the issue, please comment and ask for the issue to be reopened if the problem persists.
