### ISSUE TITLE
data-factory-release-notes.md - incorrect sample

### ISSUE THREAD

**Issue by idofl** [Azure/azure-content#4090]
Under "New dataset JSON", the interval value is a string ("1"), whereas it should be a number (1).

In addition, the "Edit on GitHub" link from the documentation (https://azure.microsoft.com/en-us/documentation/articles/data-factory-release-notes/) is broken.

**Comment by deneha** [comment]
@idofl Thank you for raising this issue!  The 404 error has been escalated.  

@spelluru Could you please assist?

**Comment by spelluru** [comment]
@idofl - thanks for reporting the issue. I have fixed and submitted a PR. You should see the change tomorrow. Thanks.
