### ISSUE TITLE
Get-AzureCheckDnsAvailability cmdlet is renamed

### ISSUE THREAD

**Issue by alexandair** [Azure/azure-content#4093]
[https://github.com/Azure/azure-content/blob/master/articles/virtual-machines/virtual-machines-ps-create-preconfigure-windows-resource-manager-vms.md](https://github.com/Azure/azure-content/blob/master/articles/virtual-machines/virtual-machines-ps-create-preconfigure-windows-resource-manager-vms.md)

Get-AzureCheckDnsAvailability cmdlet is renamed to Test-AzureDnsAvailability.
```PowerShell
Get-AzureCheckDnsAvailability -DomainQualifiedName $domName -Location $loc
```

**Comment by deneha** [comment]
@alexandair Thanks for raising this issue.  I'll have one of our team review.

@KBDAzure Could you please review this issue?

**Comment by KBDAzure** [comment]
Thanks for reporting this. I also saw the Disqus comment in which this issue was reported. I'll make an update to the article to note this.

**Comment by KBDAzure** [comment]
I've updated the article and submitted it for publishing. The update should be published tomorrow, 8/18.

**Comment by KBDAzure** [comment]
@deneha - this issue is fixed and the updated article is published. https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-ps-create-preconfigure-windows-resource-manager-vms/
Please close this issue.
