### ISSUE TITLE
Add Android, Cordova, and iOS in Swift to Mobile App Services

### ISSUE THREAD

**Issue by James-Parsons** [Azure/azure-content#4094]
Currently, the Azure Mobile App Service docs suck. They provide docs for:

* iOS (Objective-C)
* Xamarin Android
* Xamarin iOS
* Windows

A lot of these are not even in **all** of the tutorials. Could you nice people add Cordova and Android client docs along with providing iOS code in Swift?

**Comment by deneha** [comment]
@James-Parsons Thanks for the feedback.  Are there any documents in particular that you find unsatisfactory?  I can pass on this feedback if you can give me some more specific examples of where you feel improvement is needed.

**Comment by James-Parsons** [comment]
It would be nice if I could see Android and Cordova clients on at least
"Getting Started" "Push Notifications" and "Authentication" sections

**Comment by deneha** [comment]
@James-Parsons Ok, I'll pass along this feedback to the manager of this content area.  Are there any particular tutorials you're using right now?

**Comment by davidwrede** [comment]
Hi @James-Parsons, 

Thanks for the feedback on what versions of our tutorials you'd like to see. 

We're currently in the midst of a doc push at the moment, but rest assured, we already have Android, Cordova, and Swift versions of our tutorials in our backlog. We'll start on them as soon as the various client bits and this doc push are done.

**Comment by James-Parsons** [comment]
Cool, thanks

**Comment by James-Parsons** [comment]
Has there been any progress?
