### ISSUE TITLE
Broken link on media service doc

### ISSUE THREAD

**Issue by tysonn** [Azure/azure-content#4108]
The first link on this article throws a 404: https://azure-staging.microsoft.com/en-us/documentation/articles/media-services-portal-get-started-with-live/

@Juliako - can you please fix

**Comment by Juliako** [comment]
Fixed https://acom-sandbox.azurewebsites.net/en-us/documentation/articles/media-services-portal-get-started-with-live/

**Comment by davidwrede** [comment]
verified on production site
