### ISSUE TITLE
doc content issue: customer usage of azure not appropriate?

### ISSUE THREAD

**Issue by squillace** [Azure/azure-content#4120]
@felixrieseberg; @ahmetalpbalkan; @jasonnewyork 

I noted [this PR (4105)](https://github.com/Azure/azure-content/pull/4105#issuecomment-126412430) in the repository, rejected with the statement:

```
Hey Felix -

We can't publish your article to azure.com because we can't promote tools on our official storage documentation site that the storage team does not support themselves.

For this reason, we need to close your PR.
```

Across azure.com, we (Microsoft) publish tons of articles that have to do with tools that others have written and have nothing to do with official sponsorship or support (there's an entire open-source content slice that has to do with all apis we expose, for example), but rather with helping customers get done what they want to get done. 

In this case, it is an MS group that is using the storage apis to help the customers do their work. I have to say that while I totally believe there are "promotions" that do not belong as articles, this certainly is not one. Can we come up with a better argument about why customers do not deserver to discover this tool to help them use Azure and Azure Storage more effectively?

**Comment by ahmetalpbalkan** [comment]
Agreed on the fact that we write docs on quite many 3rd party software that has nothing to do with us

In this case, Felix's pull request does not make it clear if this tool is by Microsoft or not, or if it supported/endorsed by Microsoft or not. As a customer, security and data collection on such a tool would matter to me a great deal, and I am not sure if there are certain security audits in place to endorse a storage client (I know that storage team has endorsed various 3rd party clients in the past in their blog posts). I am also sure some of the commercial storage explorer clients built by certain 3rd parties were not endorsed or mentioned at all either. 

In this case if we are going to put this out, it should either have a disclaimer explaining its relation to Microsoft and support level, or should probably be audited by Storage team if it's a good fit and complies their certifications and meets their security/data collection bar. In either circumstances, I don't think this should be rejected from docs, although the docs may require alterations like the disclaimer to begin with. 

In my opinion the latter should happen, given the fact that this tool provides a great deal of cross platform support which we are currently missing for Storage Explorers. However all this should not settled, we can always embrace one thing over another over time and we may adopt this as our official storage explorer on desktop platforms. But this discussion should be done with the storage team (let me know if you have problems convincing them.) :-) 

-My 2c

**Comment by felixrieseberg** [comment]
I share the same concerns about security and support as the storage team, which is why __we're never calling Azure directly - we're exclusively using the Azure Storage Node SDK__. In addition, the whole app is offline.

It's essentially just a GUI over the Storage SDK, because all developers on OS X or other Unix flavors currently have no way to actually interact with Azure Storage from a graphical interface.

@ahmetalpbalkan: Good feedback! If that would help, I'll be happy to write a version that makes it more obvious what the support levels are. I'd love an intro - I'm sure that if I show our code to any engineer for about 5 minutes, it'll become glaringly obvious how harmless, simple, and just tied to the official SDK the whole thing is.

**Comment by tamram** [comment]
We have added a pointer to this storage explorer to the blog post where we list storage explorers; see http://blogs.msdn.com/b/windowsazurestorage/archive/2014/03/11/windows-azure-storage-explorers-2014.aspx. At this time this is where we maintain our list of storage explorers. We can look into adding these to our documentation as a list. But to add content for this individual tool to our documentation for storage would imply that this tool was supported by the storage team, and that is not the case today.

Although this tool is useful in that it is cross-platform, it does not currently support queues or tables, and so is less full-featured than other tools that are available to customers today (some of which have also been developed internally). I imagine you are working on adding this support.

In the future, please just ask us before writing a new article such as this one. We do want to encourage community contribution to the azure site, and it's great that you've written a cross-platform tool, but we also have our own policies for what we include in our official documentation.

**Comment by deneha** [comment]
Closing at request of @tamram
