### ISSUE TITLE
Rollover text in JSON editor is missing, unclear, and incomplete/incorrect

### ISSUE THREAD

**Issue by GuardRex** [Azure/azure-content#4140]
Rollover text in the JSON editor frequently doesn't provide any helpful information.

For example:
* "inputs" yields "Inputs"
* "policy" yields "Policy"
* "scheduler" yields no rollover text
* "availability" yields "Scheduler of the table" (meaningless)
* "published" yields "Table is published to Enterprise Data Directory" (meaningless)
* "timeout" yields a comment with text that reads "If a value is specified ...", but I think it should be "If no value is specified ..."?

The rollovers are very helpful (time saving) when working with the JSON, so I hope the team will go back and flesh out those statements with helpful, complete explanations and tips.

**Comment by tysonn** [comment]
@GuardRex - Thanks for filing this... I can't tell which article in our repo this feedback is about - could you add a link to the article?

**Comment by GuardRex** [comment]
@tysonn Hi ... It's not so much the documentation. I sort of filed this in the wrong place. It might be better as a UserVoice request. The problem is with the rollover text in the JSON editor of ADF itself ... in the Azure portal. When you rollover the elements in the editor, these pop-up messages were put in as an afterthought in many cases. Since this doesn't really deal with the online documentation, would it be best for me to open this at UserVoice?

**Comment by GuardRex** [comment]
I posted this request at [UserVoice](http://feedback.azure.com/forums/270578-azure-data-factory/suggestions/9151462-rollover-text-in-json-editor-is-missing-unclear).
