### ISSUE TITLE
Azure Table Storage key translation element name is unclear and rollover text is not helpful

### ISSUE THREAD

**Issue by GuardRex** [Azure/azure-content#4141]
First off, I think it was a mistake to have a separate system for setting `PartitionKey` and `RowKey` values in the `sink` section, when you had a system setup in the `translator` area specifically for the purpose of translating fields (columns) when reading and writing entities. When I first tried to get a `PartitionKey` to come from another field in my source table (`NewPKey` in this example), I incorrectly tried to do it like this ...
```
"translator": {
"type": "TabularTranslator",
"columnMappings": "NewPKey: PartitionKey, RowKey: RowKey, Value: Value"
}
```
... of course, that didn't work. For logical consistency and simplicity, I wish that all field (column) translations had been done that one way.

Ok, so the team decided to have a separate system for Azure Table Storage keys. You actually specify the field from which to draw the `sink` entity keys using `azureTablePartitionKeyName` and `azureTableRowKeyName`.

I think you should consider changing the name of that element. It is in the docs, but it would have been helpful to have the name be more meaningful. I would suggest anything like something from the following list, which would be more meaningful ...
* azureTablePartitionKeySource
* azureTablePartitionKeySourceField
* azureTablePartitionKeyValueSource
* azureTablePartitionKeyValueSourceField
* azureTablePartitionKeyDataSource
* azureTablePartitionKeyDataSourceField

... and similarly for RowKey. Also, keeping in mind that when dealing with a NoSQL, schema-less storage like Azure Table Storage, we really should be using the word "field" and not the word "column." There are no columns in schema-less data, per se.

... and please fix the rollover text. The rollover text for `azureTablePartitionKeyName` states `Azure table partition key name`. Make it say something like ...
```
The field to be used for each entity's PartitionKey value. Example: If you have a field 
named NewPKey; and you want that field to supply the values for PartitionKey in the 
sink dataset, then specify NewPKey for this element.
```

**Comment by tysonn** [comment]
@tamram & @jasonnewyork - Tamra/Jason, could you take a look at this?

**Comment by tamram** [comment]
@GuardRex, can you tell us which article your comments above refer to?

**Comment by GuardRex** [comment]
@tamram I opened this in the wrong place. It's clear to me now that this forum is for doc-related comments. I'll open a UserVoice issue on this for ADF.

**Comment by GuardRex** [comment]
I posted it here: http://feedback.azure.com/forums/270578-azure-data-factory/suggestions/9298137-azure-table-storage-key-field-translations-json-e
