### ISSUE TITLE
Azure pricing issue during preview

### ISSUE THREAD

**Issue by GuardRex** [Azure/azure-content#4142]
I understand this is a documentation repo, but no answers are really being supplied in the Disqus forum. I was hoping I could get an answer here.

My understanding is that during preview, we should get 5 free activities per month. I only have one pipeline with a dataset source (an Azure Table Storage table), one activity (a Copy activity), and one dataset sink (also another Azure Table Storage table). Apparently, the definition of the word "free" has changed, or I missed something. :smile: 

Why am I seeing some billing for ADF under this scenario?
![capture](https://cloud.githubusercontent.com/assets/1622880/9027328/2a790796-3917-11e5-8363-94213adb553d.png)

**Comment by tysonn** [comment]
Hi Luke - Could you please contact the Azure product team with this billing question? Their number is 1-800-867-1389, and option #2 is for billing questions. Sorry the doc team can't help with this one.

**Comment by GuardRex** [comment]
No worries. It's pennies ... it just didn't make sense that MS was saying ADF is "free," and I see a charge right now for using it.
