### ISSUE TITLE
Azure Batch VM's relative to HDInsight VM's with ADF

### ISSUE THREAD

**Issue by GuardRex** [Azure/azure-content#4143]
For HDInsight, it's clear that the underlying VM's are provisioned, used, and de-provisioned. It looks like Azure Batch VM's are provisioned outside of ADF such that ADF cannot de-provision them after a pipeline has run. Is that correct? If so, I recommend a line or two be added here ...
https://azure.microsoft.com/en-us/documentation/articles/data-factory-use-custom-activities/#AzureBatch
and here ...
http://azure.microsoft.com/blog/2015/05/01/azure-data-factory-updates-execute-adf-custom-net-activities-using-azure-batch/
to that effect.

Also, it would be good to extend the docs to talk a little about how Azure Batch can be used in an on-demand scenario with ADF. I'm just thinking in terms of minimizing Azure charges when ADF pipelines that use Azure Batch are not actually processing data.

**Comment by tysonn** [comment]
@JennieHubbard & @spelluru - Could you follow up on this feedback about Azure Data Factory docs? Thanks!

**Comment by spelluru** [comment]
@GuardRex - Thank you very much for the feedback. I will update the documentation article in a day or two. I will also contact the blog post owner to have the post updated soon. 

Thanks again,
Sreedhar

**Comment by GuardRex** [comment]
@tysonn @spelluru Thanks. I'm learning about Azure Batch now. Except for the expansion of docs dealing with using Batch with ADF, scaling of the Azure Batch is apparently totally controlled by the Azure Batch fabric. It sounds like Batch VM's spin up and down under Batch on-demand. It's unclear to me right now if Batch is what I'm going to need to work around the limitations of ADF querying when working with ATS data. I posted a few notes on my needs for ATS-ADF here: http://feedback.azure.com/forums/270578-azure-data-factory/suggestions/9142345-azure-table-storage-query-system-completely-inadeq

Right now, I'm trying to figure out if I can do what I want with an sproc activity in the pipeline ... but I sort of doubt it, because it looks like the source dataset coming from ATS will come into the pipeline without filtering on my datetime-based RowKey. The RowKey of my ATS table is created from Date.MaxValue - Date.UtcNow, so it's reverse ordered with most recent entities on top for each PartitionKey.

What I need to do is filter the ATS table by this datetime-based RowKey before the ADF activity gets it and puts it into SQL Azure. As you know, there is no way that ADF's limited querying capabilities can do anything like that for an ATS dataset. That's why I was wondering if Azure Batch would be the way to go.

**Comment by GuardRex** [comment]
@spelluru It looks like the Azure Batch Pool must have at least one running VM. It can auto-scale up and down from there on demand. Since a Batch Pool can't have zero active VM's and only spin one up when ADF has work to do, it's not a good solution for me. I'm only trying to run one ADF pipeline once per day. It would be a waste to have a VM running all day and all night for one pipeline doing a one-shot activity that would only take a few minutes to complete.

Regarding the docs, I found one thing confusing/missing ...

In the [Azure doc](https://azure.microsoft.com/en-us/documentation/articles/data-factory-use-custom-activities/#AzureBatch) and @gauravmalhot's [blog](http://azure.microsoft.com/blog/2015/05/01/azure-data-factory-updates-execute-adf-custom-net-activities-using-azure-batch/)), where they speak about tying Azure Batch into ADF, they both sort of make an uncomfortable jump from spinning up the Azure Batch Pool right to configuring the ADF pipeline activity with the blob containers `customactvitycontainer` with `MyDotNetActivity.zip` and `blobcustomactivitycontainer`.

I'm new to both services, and the thing that jumps to mind is that once you setup the blob containers and have your zipped package in place, you don't need to sweat messing around with Azure Batch Job(s) and Task(s). Apparently, ADF takes care of it. However, what's going on behind the scenes? If your Azure Batch Pool is configured to auto-scale, will ADF-Azure Batch auto-scale by slice? How will it do that? ... and I guess it will be ok to have only one VM running in Azure Batch and it will just process the slices as ADF shoots them over (guessing).  

I think additional documentation on how ADF with Azure Batch takes care of the Job(s) and Task(s) would be very helpful there ... somewhere around Step 4 of the [Azure doc](https://azure.microsoft.com/en-us/documentation/articles/data-factory-use-custom-activities/#AzureBatch) and right around "Associate this linked service with the custom activity." in @gauravmalhot's blog post.

**Comment by spelluru** [comment]
It’s possible to create an Azure batch pool with 0 dedicated VMs and an auto-scale formula. Please see https://azure.microsoft.com/en-us/documentation/articles/batch-automatic-scaling/ for more information on automatic scaling. 

HTH,
Sreedhar
