### ISSUE TITLE
Vnet to VNet

### ISSUE THREAD

**Issue by sahin** [Azure/azure-content#4148]
https://github.com/Azure/azure-content/blob/master/articles/vpn-gateway/virtual-networks-configure-vnet-to-vnet-connection.md

@deneha 

this page uses the old UI, old command line and not ARM. 

can u update it?

**Comment by deneha** [comment]
@sahin Thanks for raising this issue.  You are welcome to suggest changes to documentation using the GitHub functionality.  We'll forward the suggestions to the author of the page.

**Comment by sahin** [comment]
Unfortunately, there is no documentation with the new arm and new virtual networks, I connected to support , I asked for hands on help. if I have anything I will send, but if the author can be quick and update for the new ARM and new virtual network. it will be super great. We really need it.

**Comment by deneha** [comment]
@sahin I'll let our team know about this request.

@cherylmc Could you please review this issue?

**Comment by cherylmc** [comment]
I'll check with the product team on this. This particular article would not be updated, as it is valid for the classic Service Management VNets, which still exist in production for many customers. I would write a new article specifically for Resource Manager. The first article would likely be PowerShell.

**Comment by sahin** [comment]
@cherylmc thanks. I contacted the support but they seem they cannot help that much. I really really need vnet - vnet Resource Manager very urgently. When do you think u can write one?

**Comment by cherylmc** [comment]
We are working on that at the moment. It looks like I should have something ready next week.

**Comment by sahin** [comment]
@cherylmc , I was getting hands on help from azure support. 

```
old vn  is 20.0.0.0/22 mll-us-east
Gateway 20.0.0.128/29


new ARM VN 10.0.0.0/22 mll-eastus2-network
Gateway subnet 10.0.4.0/29 # 10.0.4.0 - 10.0.4.7


    New-AzureLocalNetworkGateway -Name mll-us-east-local-network-old `
    -Location "East US" -AddressPrefix "20.0.0.0/22" `
    -GatewayIpAddress "191.237.86.175" -ResourceGroupName mll-eastus2-resource

    $ipaddress = New-AzurePublicIpAddress -Name mll-eastus2-network-gateway-ip `
    -ResourceGroupName mll-eastus2-resource -Location "East US 2" `
    -AllocationMethod Dynamic

    # create a sub net in the new portal UI
    # Gateway subnet 10.0.4.0/29

    $subnet = Get-AzureVirtualNetworkSubnetConfig -Name GatewaySubnet `
    -VirtualNetwork (Get-AzureVirtualNetwork -Name mll-eastus2-network -ResourceGroupName mll-eastus2-resource)

    # 10.0.4.1 the first ip of the gateway subnet of new ARM vnet

    $ipconfig = New-AzureVirtualNetworkGatewayIpConfig `
    -Name ipconfig -PrivateIpAddress 10.0.4.4 `
    -SubnetId $subnet.id -PublicIpAddressId $ipaddress.id


    New-AzureVirtualNetworkGateway -Name mll-eastus2-network-gateway -ResourceGroupName mll-eastus2-resource `
    -Location "East US 2" -GatewayType Vpn -IpConfigurations $ipconfig `
    -EnableBgp $false -VpnType RouteBased

    Get-AzurePublicIpAddress -Name mll-eastus2-network-gateway-ip -ResourceGroupName mll-eastus2-resource


    Set-AzureVNetGatewayKey -VNetName mll-us-east `
    -LocalNetworkSiteName mll-eastus2-network -SharedKey XXXX

    ------

    Switch-AzureMode AzureResourceManager

    $vnet01gateway = Get-AzureLocalNetworkGateway -Name mll-us-east-local-network-old -ResourceGroupName mll-eastus2-resource

    $vnet02gateway = Get-AzureVirtualNetworkGateway -Name mll-eastus2-network-gateway -ResourceGroupName mll-eastus2-resource

New-AzureVirtualNetworkGatewayConnection -Name us-east2-us-east-connection `
    -ResourceGroupName mll-eastus2-resource -Location "East US 2" -VirtualNetworkGateway1 $vnet02gateway `
    -LocalNetworkGateway2 $vnet01gateway -ConnectionType IPsec `
    -RoutingWeight 10 -SharedKey 'XXXX'

````

**Comment by cherylmc** [comment]
Sounds like you are good to go, then! The article should be out there sometime later this week.

**Comment by cherylmc** [comment]
I'll ping back with the link when it's live. It looks like your settings are slightly different than what I am working with, so I'll run them by the product group PM that owns the technology. Thanks for providing!

**Comment by sahin** [comment]
@cherylmc thx.

**Comment by cherylmc** [comment]
Here's the link to the new doc. Hope this helps! https://azure.microsoft.com/documentation/articles/vpn-gateway-vnet-vnet-rm-ps/

**Comment by deneha** [comment]
@sahin It looks like this issue has been resolved.  I'm closing this issue.  Please comment if the issue should be reopened.
