### ISSUE TITLE
Update template for Azure Batch linked service in Azure Data Factory document

### ISSUE THREAD

**Issue by GuardRex** [Azure/azure-content#4149]
On the page: https://azure.microsoft.com/en-us/documentation/articles/data-factory-use-custom-activities/#AzureBatch ... in the "Using Azure Batch linked service" section ... there is a JSON template for the linked service. It looks like this:
```JSON
{
    "name": "AzureBatchLinkedService",
    "properties": {
        "type": "AzureBatchLinkedService",
        "accountName": "<Azure Batch account name>",
        "accessKey": "<Azure Batch account key>",
        "poolName": "<Azure Batch pool name>",
        "linkedServiceName": "<Specify associated storage linked service reference here>"
  }
}
```
It looks like the `type` value is wrong. I think it should be `AzureBatch`.

**Comment by deneha** [comment]
@GuardRex Thanks for raising this issue.

@spelluru Could you please assist?

**Comment by spelluru** [comment]
@GuardRex - I will fix this issue in a minute along with a few other issues in the article (for example: • Batch URL becomes regional from https://<account>.batch.core.windows.net to https://<account>.<region>.batch.azure.com. Thanks.

**Comment by GuardRex** [comment]
@spelluru ... and it says 
```
You can download and use the Azure Batch Explorer tool (or) ...
```
 ... but that makes it sound like the Azure Batch Explorer tool is an executable. You might want it to say:
```
You can download, compile, and use the Azure Batch Explorer tool (or) ...
```

**Comment by spelluru** [comment]
@GuardRex  - Fixing it right now. The updated article should go live tomorrow. Thank you very much the feedback.

**Comment by GuardRex** [comment]
@spelluru Sure thing. Thanks for jumping right on it. I'll be keeping an eye out for response to my [Uservoice](http://feedback.azure.com/forums/270578-azure-data-factory/suggestions/9142345-azure-table-storage-query-system-completely-inadeq) call for more ATS datetime key filtering capabilities. ATS is definitely it's own wild beast! :smile:
