### ISSUE TITLE
Examples and docs for Azure Data Factory functions don't show combined functions in $$Text.Format() calls

### ISSUE THREAD

**Issue by GuardRex** [Azure/azure-content#4152]
On the MSDN page: https://msdn.microsoft.com/en-us/library/azure/Dn835056.aspx ... and elsewhere when the ADF docs refer to functions, there is no text or examples of combining functions in `$$Text.Format()` calls. I was trying to use this:
```
$$Text.Format('PartitionKey eq \\'my_pkey_filter_value\\' and 
RowKey ge \\'{0:yyyy-MM-dd HH:mm:ss}\\'', $$Time.AddHours(SliceStart, -6))
```
and the exception comes back that the parser is choking on it. It should be written like this:
```
$$Text.Format('PartitionKey eq \\'my_pkey_filter_value\\' and 
RowKey ge \\'{0:yyyy-MM-dd HH:mm:ss}\\'', Time.AddHours(SliceStart, -6))
```
**The docs don't explain that any inner function call doesn't need the "$$" prefix. Just one added example to this page on the functions would help.**

Also, please keep in mind that we need a way to subtract SliceStart (and SliceEnd) from Date.MaxValue (12/31/9999 23:59:59.9999999) in order to build effective datetime queries with Azure Table Storage keys. This isn't a "doc" issue, so I opened it at [Uservoice](http://feedback.azure.com/forums/270578-azure-data-factory/suggestions/9142345-azure-table-storage-query-system-completely-inadeq); but it's killing me today that I don't have that capability. We need to be able to mirror queries like this from VB/C# code:
```
RowKey le '" & (Date.MaxValue - DateAdd(DateInterval.Hour, -6, Date.UtcNow)).ToString() & "'"
```
... something like ...
```
$$Text.Format('PartitionKey eq \\'my_pkey_filter_value\\' and 
RowKey le \\'{0}\\'', Time.MaxValue - Time.AddHours(SliceStart, -6))
```
... note that values in the RowKey come out formatted this way: `2916246.05:51:13.9999999` for example, when making these comparisions, which is why you see I have `{0}` there without a date format.

**Comment by deneha** [comment]
@GuardRex Thanks for raising this issue.

@spelluru Could you please review this issue?

**Comment by spelluru** [comment]
@GuardRex - Great suggestion. I will update the MSDN topic you pointed and also the new ACOM (Azure.com) article we just published last Friday: https://azure.microsoft.com/en-us/documentation/articles/data-factory-scheduling-and-execution/. Thank you.

**Comment by GuardRex** [comment]
@spelluru Cool. Thanks.
