### ISSUE TITLE
Typo in Azure Data Factory doc

### ISSUE THREAD

**Issue by GuardRex** [Azure/azure-content#4154]
In the Azure Data Factory tutorial at [Tutorial: Create and monitor a data factory using Data Factory Editor](https://azure.microsoft.com/en-us/documentation/articles/data-factory-get-started-using-editor/)

On the "Using Data Factory Editor" tab ...

Under the "Create output table" section ...

It looks like ...
```
Note the following:
location type is set to AzureSQLTableLocation.
```
should be
```
Note the following:
location type is set to AzureSQLTable.
```

**Comment by deneha** [comment]
@GuardRex Thanks for raising the issue.

@spelluru Could you please assist?

**Comment by spelluru** [comment]
Thanks @GuardRex. I will update it today and take it live tomorrow. Appreciate your feedback.

**Comment by GuardRex** [comment]
@spelluru Sure thing. There's one more there on the same page that looks wrong:

In the `ADFTutorialPipeline` template, it shows this "Policy" section:
```
"Policy": {
  "concurrency": 1,
  "executionPriorityOrder": "NewestFirst",
  "style": "StartOfInterval",
  "retry": 0,
  "timeout": "01:00:00"
}
```
... but `style` was apparently removed at some point ... I don't see it in the JSON editor in the Azure portal.

Also, That `writeBatchTimeout` in the `sink` section ...
```
"sink": {
  "type": "SqlSink",
  "writeBatchSize": 10000,
  "writeBatchTimeout": "60:00:00"
}
```
... set to `60:00:00` looks wrong. If that's supposed to be hours, minutes, seconds, shouldn't it be `01:00:00`?

**Comment by spelluru** [comment]
Fixed all the issues except the following. You should see the changes tomorrow. 

style: Editor works fine for me with style. I even press CTRL + Spacebar to see the property. Intellisense also shows the values such as StartOfInterval. 

Thanks.

**Comment by GuardRex** [comment]
@spelluru Strange ... I'm not seeing it. Well, it doesn't really affect me. I just need to specify `style` for the `scheduler` element. Anyway ... here's what the portal is showing me if I try to add a `style` to `policy` ... it doesn't find it:
![capture](https://cloud.githubusercontent.com/assets/1622880/9051811/a1a1a99a-3a25-11e5-94f3-ca04fc734cad.png)

**Comment by GuardRex** [comment]
Oh! ... and I just noticed that the template has `Policy` as the element, but I think they are all supposed to be lowercase, right? ... `policy`?

**Comment by spelluru** [comment]
I was testing the property in the availability section of the dataset. Now, I tested in the policy section of a pipeline JSON, I see the issue you are seeing. I looked at the latest JSON in the https://azure.microsoft.com/en-us/documentation/articles/data-factory-create-pipelines/ article. The style element has been removed. I am going to remove it from the tutorial. Thanks.

**Comment by GuardRex** [comment]
Oh, ok, cool. I thought my Azure portal was playing a trick on me! :smile:
