### ISSUE TITLE
Broken link in Azure Data Factory Use Case page

### ISSUE THREAD

**Issue by GuardRex** [Azure/azure-content#4158]
Hello @spelluru,

Got one for ya ... On the page: https://azure.microsoft.com/en-us/documentation/articles/data-factory-customer-profiling-usecase/

The link to  www.microsoft.com/cortanaanalytics is broken. I think it should point to ...

http://www.microsoft.com/en-us/server-cloud/cortana-analytics-suite/Overview.aspx

**Comment by spelluru** [comment]
Thank you. I noticed it today and updates the article. Changes should go live in a day.

Sent from my iPhone

On Aug 4, 2015, at 1:29 AM, Luke Latham <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @spelluru<https://github.com/spelluru>,

Got one for ya ... On the page: https://azure.microsoft.com/en-us/documentation/articles/data-factory-customer-profiling-usecase/

The link to www.microsoft.com/cortanaanalytics<http://www.microsoft.com/cortanaanalytics> is broken. I think it should point to ...

http://www.microsoft.com/en-us/server-cloud/cortana-analytics-suite/Overview.aspx

-
