### ISSUE TITLE
I found this broken link - https://azure.microsoft.com/en-us/documentation/articles/cdn-how-to-use/

### ISSUE THREAD

**Issue by mauricionr** [Azure/azure-content#4187]
https://azure.microsoft.com/en-us/documentation/articles/cdn-how-to-use/

**Comment by deneha** [comment]
@mauricionr Thanks for raising this issue.

@Juliako Could you please assist?

**Comment by Juliako** [comment]
@mauricionr thank you, I am in the process of fixing it.

**Comment by mauricionr** [comment]
Thanks @deneha and @Juliako !

**Comment by deneha** [comment]
@mauricionr The link has been changed:  https://azure.microsoft.com/en-us/documentation/articles/cdn-how-to-use-cdn/  

Please let us know if this doesn't solve your issue by leaving a comment.  I'm closing this issue because the issue seems resolved.

**Comment by mauricionr** [comment]
Thanks @deneha
