### ISSUE TITLE
Typos in  SQL Server Stored Procedure Activity in Azure Data Factory page

### ISSUE THREAD

**Issue by GuardRex** [Azure/azure-content#4191]
Hello @spelluru 

I have another nit for ya ...

In the page [SQL Server Stored Procedure Activity](https://azure.microsoft.com/en-us/documentation/articles/data-factory-stored-proc-activity/), there are two minor typos:

In Step 4 of the Example, `"typeproperties"` should be `"typeProperties"` and `" SqlServerStoredProcedure "` should be `"SqlServerStoredProcedure"` (no spaces around the value).

**Comment by spelluru** [comment]
Thank you. Fixing it today. Changes will go live tomorrow.
