### ISSUE TITLE
What is the limit of user defined routes in an azure vnet routing table?

### ISSUE THREAD

**Issue by MalteJ** [Azure/azure-content#4223]
How many user defined routes may I add to an azure routing table?
Here it only says the maximum number of routes that is displayed is 800.
https://github.com/Azure/azure-content/blob/master/articles/virtual-network/virtual-networks-udr-how-to.md

So how many routes may I create?

**Comment by MalteJ** [comment]
Can I use those routes to set up a Kubernetes network, where every VM has a /24 subnet that is used by Docker Containers?
Let's say my VMs have IPs in the subnet `192.168.0.0/24`

| VM   | VM IPv4 Address | Containers' IPv4 Addresses |
|------|-----------------|----------------------------|
| vm-1 | 192.168.0.1     | 10.0.1.0/24                |
| vm-2 | 192.168.0.2     | 10.0.2.0/24                |
| vm-3 | 192.168.0.3     | 10.0.3.0/24                |

and then I would add routes

    Get-AzureRouteTable KubernetesRouteTable `
        |Set-AzureRoute -RouteName Minion-1 -AddressPrefix 10.0.1.0/24 `
        -NextHopType VirtualAppliance `
        -NextHopIpAddress 192.168.0.1

    Get-AzureRouteTable KubernetesRouteTable `
        |Set-AzureRoute -RouteName Minion-1 -AddressPrefix 10.0.2.0/24 `
        -NextHopType VirtualAppliance `
        -NextHopIpAddress 192.168.0.2

    Get-AzureRouteTable KubernetesRouteTable `
        |Set-AzureRoute -RouteName Minion-1 -AddressPrefix 10.0.3.0/24 `
        -NextHopType VirtualAppliance `
        -NextHopIpAddress 192.168.0.3

The question is: How many VirtualAppliance routes are allowed?
How good is the performance?

**Comment by deneha** [comment]
@MalteJ Thank you for raising this issue.  I'll contact a member of our team to review your question.

@telmosampaio Could you please assist?

**Comment by telmosampaio** [comment]
The 800 limit is for BGP routes. You can have up to 100 routes (by default) in a route table, and 100 route tables per region per subscription. If you need more, you can contact support.

**Comment by deneha** [comment]
@MalteJ We're closing this issue.  If you need further help, please contact support.  If you have a document content issue, please raise the issue here.  Thank you!
