### ISSUE TITLE
expressroute-exp-connectivity-workflow.png 

### ISSUE THREAD

**Issue by kevinapurcell** [Azure/azure-content#4287]
expressroute-exp-connectivity-workflow.png step 3 bullet 2 says "Customer proides list of prefixes..." this should say "Customer provides list of prefixes..."

**Comment by deneha** [comment]
@kevinapurcell Thanks for raising this issue.  I'll contact the author.

@cherylmc Would you please assist?  The issue in question is located in this article: https://azure.microsoft.com/en-us/documentation/articles/expressroute-configuring-exps/

**Comment by cherylmc** [comment]
Thanks! I'll have them create me a new graphic for that. Good catch!

**Comment by deneha** [comment]
@kevinapurcell Thanks again for raising this issue.  Our content plan includes the removal of this topic, so we're going to close this issue.
