### ISSUE TITLE
Preferable should be preferably

### ISSUE THREAD

**Issue by MarcRice** [Azure/azure-content#4406]
In the Staging server section, the sentence "This second server can preferable be located in a different datacenter since no infrastructure is shared with the primary server." should read "This second server can preferably be located in a different datacenter since no infrastructure is shared with the primary server. "

**Comment by deneha** [comment]
@MarcRice Thanks for raising this issue.  Could you please provide the URL of the page?

**Comment by tysonn** [comment]
Fixed in https://azure.microsoft.com/en-us/documentation/articles/active-directory-aadconnect-topologies/.  Thanks for calling this out.
