### ISSUE TITLE
Mobile Services iOS .Net Get Started Tutorial Errors

### ISSUE THREAD

**Issue by JMarson** [Azure/azure-content#4454]
In the tutorial - https://azure.microsoft.com/en-us/documentation/articles/mobile-services-dotnet-backend-ios-get-started-data/

The line:
self.table = [self.client tableWithName:@"TodoItem"];
generates the error: "No visible @interface for 'MSClient' declares the selector 'tableWithName:'"

The MSClient.h file that comes with the sample project download includes a method 'getTable:', so either the tutorial or the sample project files need to be updated.

Also, there are issues with building project on iPhone 5S + (x86_64 Architecture Errors). Outdated framework included in the project?

**Comment by deneha** [comment]
@JMarson Thank you for raising this issue.  I will have the author of the document review your question.

@krisragh Would you please review this question?

**Comment by krisragh** [comment]
@JMarson: where did you download the Xcode project from? I just create a new Azure Mobile App at the preview Azure portal, and downloaded the Objective-C quickstart Xcode project. In that file, I see a definition for only tableWithName, none for getTable, in MSClient.h.  Can you please try again?

**Comment by JMarson** [comment]
@krisragh I downloaded it from clicking one of the two links that say 'GetStartedWithData iOS app' within the page section 'Download GetStartedWithData Project'. They both point to the download URL is http://go.microsoft.com/fwlink/p/?linkid=268622&clcid=0x409.

**Comment by krisragh** [comment]
@JMarson: you are right! This is indeed an outdated version of code you're seeing, with an outdated framework included as well. I'm sorry about this bug -- I'm investigating what we can do here. (Note that if you download a quickstart project straight from the portal for your mobile backend, it'll have the latest code and framework integrated into it, but I realize that's not the focus of this tutorial.) If I can be of further immediate assistance to help unblock you, please feel to also contact me directly at krisragh at microsoft dot com.

**Comment by JMarson** [comment]
All good! Just letting you know of the error! Thanks @krisragh

**Comment by tysonn** [comment]
Looks like this is handled - closing the issue.
