### ISSUE TITLE
Basic File Upload 

### ISSUE THREAD

**Issue by krusk** [Azure/azure-content#4461]
I am newer to Node.js and am following this article to perform some basic blob actions:

https://azure.microsoft.com/en-us/documentation/articles/storage-nodejs-how-to-use-blob-storage/

One of those basic actions is uploading to a blob. I created a test.txt file at the same level of server.js but it doesn't seem to upload to "mycontainer". Is SAS required for this to occur/are there any other references/methods to upload via Node.js? I can create containers without issue.

    blobSvc.createBlockBlobFromLocalFile('mycontainer', 'myblob', 'test.txt', function(error, result,      response){
    if(!error){
    // file uploaded
    }
    });

**Comment by deneha** [comment]
@krusk Thanks for raising this issue.  I'll have the author review your question.

@MikeWasson Would you please review this question?  Thank you.

**Comment by krusk** [comment]
Thank you. I consoled logged the error as follows:

{ [Error: The MD5 value specified in the request did not match with the MD5 valu
e calculated by the server.
RequestId:38ac3597-0001-006b-10ad-ec495f000000
Time:2015-09-11T16:19:02.2964517Z]
  code: 'Md5Mismatch',
  userspecifiedmd5: 'iXQqCdm0Eym4ULdqdrBeAA==',
  servercalculatedmd5: 'd0/2Ml1E1yVKGggdT56vLw==',
  statusCode: 400,
  requestId: '38ac3597-0001-006b-10ad-ec495f000000' }

**Comment by tysonn** [comment]
@krusk - I've pinged some other folks on this.

**Comment by krusk** [comment]
Thanks @tysonn. I received help on SO, and am well on my way for my needs, but am still interested about the MD5 value error: http://stackoverflow.com/questions/32619369/download-file-via-webservice-and-push-it-to-azure-blob-storage-via-node-express

**Comment by tamram** [comment]
It looks like this issue was also addressed here: https://github.com/Azure/azure-storage-node/issues/78

Please update your node.js client library to version 0.6.0 to see if that fixes the problem, and let us know.

**Comment by krusk** [comment]
We are good! Thanks everyone.
