### ISSUE TITLE
2 broken links

### ISSUE THREAD

**Issue by snobu** [Azure/azure-content#4545]
In this section here both links return 404.

>Next steps
>For more information please see: Get started with Azure DNS and Delegate Domain to Azure DNS

https://azure.microsoft.com/en-gb/documentation/articles/web-sites-custom-domain-name/

**Comment by deneha** [comment]
@snobu Thank you very much for letting us know about this document issue.  I'll notify a member of our team to get it fixed.

**Comment by deneha** [comment]
@snobu These have been fixed and they're live.  Thanks again for the heads up!  Closing this issue.
