### ISSUE TITLE
Error occured in "Build your first pipeline using Azure Data Factory".

### ISSUE THREAD

**Issue by NT-D** [Azure/azure-content#4613]
# Problem
In [this tutorial](https://azure.microsoft.com/en-us/documentation/articles/data-factory-build-your-first-pipeline/), ParseException will cause.

## Repro steps
1. In [this step](https://azure.microsoft.com/en-us/documentation/articles/data-factory-build-your-first-pipeline/#prepare-azure-storage-for-the-tutorial), save "partitionweblogs.hql" with "UTF-8".
2. Run pipline process ln [this tutorial](https://azure.microsoft.com/en-us/documentation/articles/data-factory-build-your-first-pipeline-using-editor/).

## Actual result
The error below occured.
>Logging initialized using configuration in file:/C:/apps/dist/hive-0.13.0.2.1.15.1-1234/conf/hive-log4j.properties
>SLF4J: Class path contains multiple SLF4J bindings.
>SLF4J: Found binding in [jar:file:/C:/apps/dist/hadoop-2.4.0.2.1.15.1-1234/share/hadoop/common/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
>SLF4J: Found binding in [jar:file:/C:/apps/dist/hbase-0.98.0.2.1.15.1-1234-hadoop2/lib/slf4j-log4j12-1.6.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
>SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
>SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
>FAILED: ParseException line 1:0 character 'ﾃ?' not supported here
>line 1:1 character 'ﾂｻ' not supported here
>line 1:2 character 'ﾂｿ' not supported here

## Expexted result
The process is done without any problem like this.
![Screen shot flom tutorial site](https://acomdpsstorage.blob.core.windows.net/dpsmedia-prod/azure.microsoft.com/en-us/documentation/articles/data-factory-build-your-first-pipeline-using-editor/20150911052512/dataset-slice-ready.png)

## Solution
Save "partitionweblogs.hql" with "ANSI".

# Suggestion
How about to add annotation like this in [the tutorial](https://azure.microsoft.com/en-us/documentation/articles/data-factory-build-your-first-pipeline/#prepare-azure-storage-for-the-tutorial) step 1.
> Launch notepad, paste the following text, and save it as partitionweblogs.hql in the C:\adfgettingstarted folder on your hard drive with "ANSI" style. This Hive scripts creates two external tables: WebLogsRaw and WebLogsPartitioned.

If possible, please add these annotation.
* save with "ANSI" style
* Why we should save the file with "ANSI" style.

**Comment by NT-D** [comment]
just fyi
To resolve the problem, I refered [this answer](http://www.stackoverflow.dluat.com/questions/23407246/parseexceptions-when-using-hql-file-on-hdinsight) in stackoverflow.

**Comment by tysonn** [comment]
@spelluru - Could you please follow up?

**Comment by spelluru** [comment]
@NT-D - Thank you very much for sharing the solution for the issue. I will update the step in the tutorial in a day or two. Thanks again.

**Comment by NT-D** [comment]
@spelluru thansk for replying. I'm looking forward to see the update :)

**Comment by spelluru** [comment]
@NT-D - the updated article is live now. 
https://azure.microsoft.com/en-us/documentation/articles/data-factory-build-your-first-pipeline/#prepare-azure-storage-for-the-tutorial.

**Comment by NT-D** [comment]
@spelluru Looks good. thanks for quick update :)
