### ISSUE TITLE
Suggestions for improving app-service-mobile-dotnet-backend-html-get-started-preview.md

### ISSUE THREAD

**Issue by chadelofson** [Azure/azure-content#4680]
I was having some trouble working on the projects in Visual Studio 2013, but they worked just fine in Visual studio 2015.  I believe the issue is more to do with this laptop I am on then the actual projects from azure.

In the section "Download and run client project" you have an OS specific command run.  I am currently in Windows 8.1, which I ran the Start-Windows command.  That unfortunately didn't work, because if you look at the graphic below:

![htmlapptutorialclientserverdirectory](https://cloud.githubusercontent.com/assets/7609222/10286715/08f84744-6b44-11e5-851d-281051f0cd4e.PNG)

The extension for the start-windows was originally an lnk extention.  I used the start-iisexpress.ps1 script instead.  So something has changed with the downloads from Azure.

Chad

**Comment by ggailey777** [comment]
This tutorial is currently down...it will be republished updated in the near future
