### ISSUE TITLE
Suggestions for improving app-service-web-how-to-create-a-web-app-in-an-ase.md

### ISSUE THREAD

**Issue by chadelofson** [Azure/azure-content#4682]
The only difference I saw in this article is the location is no longer listed in the UI.  If you look at the following pic:

![asewebappcreation](https://cloud.githubusercontent.com/assets/7609222/10289715/a634879c-6b54-11e5-968a-6669f95d0912.PNG)

It is now "App Service Plan/Location"

I created a new service plan that would allow me to select the location and ASE like this screenshot:

![newlocation](https://cloud.githubusercontent.com/assets/7609222/10289765/f97c6adc-6b54-11e5-8c4b-e0176dcab994.PNG)

Chad Elofson

**Comment by davidwrede** [comment]
Hey @chadelofson, please go ahead and submit a PR with this change via the azure-content repo and we'll get it integrated.

Thanks,
Dave
