### ISSUE TITLE
Suggestions for improving cache-dotnet-how-to-use-azure-redis-cache.md

### ISSUE THREAD

**Issue by chadelofson** [Azure/azure-content#4687]
In the section "What is Azure Redis Cache?", the link with the text "Azure Virtual Network" gives an HTTP 404 error.

In the section "Store ASP.NET session state in the cache", there is a repeat of words.  Look at the picture below on the location:

![repeatwords](https://cloud.githubusercontent.com/assets/7609222/10294541/da5be7fc-6b6f-11e5-94f7-b4770e3b51a6.PNG)

Chad Elofson

**Comment by davidwrede** [comment]
Hi @chadelofson, please go ahead and submit a PR with this change via the azure-content repo and we'll get it integrated.

Thanks,
Dave

**Comment by chadelofson** [comment]
I can directly edit this article.  Therefore this is no longer an issue.
