### ISSUE TITLE
Where do you add a role for an AD application

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-content#5224]
https://github.com/Azure/azure-content/blob/master/articles/resource-group-create-service-principal-portal.md

Ctrl-f " Assigning the application to a role"

Where is this happening in the Portal exactly? I have no idea how to get there.

Also, why do I have to bounce back and forth between two portals to do something as simple as creating a serviceprincipal to talk to Azure APIs?

**Comment by squillace** [comment]
@BryanLa Got this?

**Comment by BryanLa** [comment]
Adding @tfitzmac for his thoughts on possibly adding some context to the article, around the steps on getting to the right place in the new Azure portal (fka: preview Portal).

@colemickens - unfortunately, as the article mentions, we are still in a transition period so some  configuration tasks span both portals, esp. when your app includes Azure AD app config. Agree that this creates a bit of a hassle, and I know the engineering team is well aware of this. In terms of *just* creating the Service Principal object though (ie: not adding it to a role to control authorization, as demonstrated in the article), you only need to do the configuration work in the Azure class portal. FWIW, here's an article with more depth on RBAC as well: https://azure.microsoft.com/en-us/documentation/articles/role-based-access-control-configure/

**Comment by colemickens** [comment]
Yes, I am able to find instructions on creating the service principal and I've indeed been in the legacy portal. However, the assignment of the Role to the Principal is my concern.

The articles show the "icon" that needs to be pressed, but they don't describe how they get to that page. It's as simple as extending the article in question to say:

"You need to navigate to a resource group or subscription in the portal. While examining its prorperties, you will see this button which can be used to configure users".

I didn't know that that button was access on the context of a resource group or subscription until getting lucky and noticing it. I was looking for "Roles" as a top level thing that I could create, etc.

**Comment by colemickens** [comment]
As I'm looking over this, the page I linked to seems to already contain the information I was seeking under "Assigning the application to a role"

Further, it links to this page which describes it in detail: https://azure.microsoft.com/en-us/documentation/articles/role-based-access-control-configure/#manage-access-using-the-azure-portal

Not sure why I wasn't able to find these the other day.

I think we can close this.

**Comment by tfitzmac** [comment]
I had updated this topic on Thursday for exactly the issue you were encountering. Thanks for the feedback.
