### ISSUE TITLE
Broken link - azure-content readme

### ISSUE THREAD

**Issue by LeCampusAzure** [Azure/azure-content#5858]
The link http://azure.github.io/guidelines.html#cla, present in https://github.com/Azure/azure-content (readme.MD), is broken

**Comment by ondine** [comment]
Broken link - azure-content readme #5858 
@LeCampusAzure 

**Link appears to be fixed:**
http://azure.github.io/guidelines/#cla

The link you copied earlier is missing the `/` after "guidelines" and the `.html` suffix has been removed.
Appears to be valid link now.

**Comment by tysonn** [comment]
Resolved
