### ISSUE TITLE
Log Topics with Chunks During Publish

### ISSUE THREAD

**Issue by scottturnbull** [Azure/azure-content#587]
This request issue is to investigate and report back whether the publishing script can be modified to flag in the log file topics that contain chunks, so that they require manual republishing in Umbraco. 

ISSUES THIS CHANGE ADDRESSES:
1. When iX updates topics in content-ppe Umbraco that contain chunks, we need to manually republish the topic before chunks it contains resolve and display on the page. Even if we can get response time improvements in the Umbraco UI, touching each file increases the time needed to publish by 30 minutes to over an hour for each publishing run. Identifying which topics need to be republished takes a significant portion of that time

2. Manually checking topics for "chunk should go here" is also error prone; frequently we miss one or more topics we should republish. This can either delay sign off, because we need to go back and refresh those topics, or lead to publishing live with unresolved chunks. This happens enough to be a significant quality issue.

SCOPE OF REQUEST
If the publishing script can identify those topics that need to be republished in Umbraco to refresh chunks (e.g. by adding a column in the log) that will help reduce time and errors in chunk publishing. This is a high priority request, as management recognizes this as a significant process cost and quality risk.

**Comment by deneha** [comment]
@scottturnbull Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
