### ISSUE TITLE
Create a Linux VM from the ground up using the Azure CLI: Error in the script

### ISSUE THREAD

**Issue by ciberado** [Azure/azure-content#6116]
Hi, new here. *I think* there is an error in the https://github.com/Azure/azure-content/blob/master/articles/virtual-machines/virtual-machines-linux-create-cli-complete.md article: instead of

```
# Associate the Public IP to the NIC
azure network nic set --public-ip-name test pip
```
it shoud be something like:

```
azure network nic set --public-ip-name testpip --resource-group TestRG testnic
```

Additionaly I'm unable to connect to the vm using ssh: the port 22 is not accesible.

**Comment by squillace** [comment]
Hi @ciberado, I'll walk through it again, for sure. As to the port, did you examine your inbound rule? It would look like:

`azure network nsg rule set --destination-port-range 22 --source-port-range "*" --protocol tcp --access allow --priority 1000 testrg testnsg testnsgrule`

One of the tricks is to make sure that you specify the source-port-range of * to allow connections initiated by any port. If you're thinking about classic deployments, the source port is NOT what you think it is. :-|

**Comment by squillace** [comment]
Hmmmm. @ciberado did we fix it in the meanwhile? I see this: https://github.com/Azure/azure-content/blob/master/articles/virtual-machines/virtual-machines-linux-create-cli-complete.md#associate-the-public-ip-and-the-network-security-group-to-the-nic

Associate the public IP and the network security group to the NIC

    azure network nic set --public-ip-name testpip testrg testnic

Bind the NSG to the NIC:

    azure network nic set --network-security-group-name testnsg testrg testnic

**Comment by ciberado** [comment]
Wow, thank you for answering so fast. And yes! Looks like it's already corrected :+1:  We can close this thread now.
