### ISSUE TITLE
Add PowerShell information to "enable remote desktop" article

### ISSUE THREAD

**Issue by brian-swan** [Azure/azure-content#648]
This article shows how to enable remote desktop for cloud services: DevCenter/Shared/Chunks/remote-desktop.md.

Since it presumes a Windows OS, it should include information about how to enable remote desktop using the Windows Azure PowerShell cmdlets (which can be done with one command: Enable-AzureServiceProjectRemoteDesktop).

**Comment by deneha** [comment]
@brian-swan We're sorry for the late reply.  Do you have the page in question still?  I cannot locate the page you're mentioning.  I'll keep this issue open for a little longer to see if we can get this resolved for you.

**Comment by brian-swan** [comment]
I haven't worked on this for a long time now...not sure where the page in question is. I suggest closing this issue.
