### ISSUE TITLE
Update Backup To Windows Azure topic 

### ISSUE THREAD

**Issue by karthikaraman** [Azure/azure-content#883]
updates to SQL Server Backup to Windows Azure Blob Storage Service Topic

**Comment by deneha** [comment]
@karthikaraman We're sorry for the late response.  Could you please give a little more information so I can help you?  We'll keep this issue open a little longer to see if we hear back from you.

**Comment by karthikaraman** [comment]
Not sure why I am getting this email. I did not make any request for this topic.

**Comment by deneha** [comment]
@karthikaraman Ok, no worries!  I'll go ahead and close the issue then.
