### ISSUE TITLE
Media Services download page suggestion

### ISSUE THREAD

**Issue by davidwrede** [Azure/azure-content#977]
http://www.windowsazure.com/en-us/develop/media-services/developer-tools/

•         I made Windows 8 and Silverlight title as link to Player Framework. Most of developers use Player Framework and I think it makes a lot of senses to promote the link onto title field - most people will click on the link rather than reading through description and after that, they will know what they need is actually Player Framework rather than Client SDK
•         I added in a few sample app link, wiki link and diagnostic tool for people to easily get started
•         I have no comment on Flash

[Player Framework for Windows 8](http://playerframework.codeplex.com/releases/view/97333) 
Player Framework enables developers to build Windows 8 Store applications that consume On-Demand and Live Smooth Streaming content with PlayReady protection delivered from Windows Azure Media Services. Moreover, it made easy for developer to monetize content by inserting standard based advertisement.  This framework is based on [Smooth Streaming Client SDK for Windows 8](http://visualstudiogallery.msdn.microsoft.com/04423d13-3b3e-4741-a01c-1ae29e84fea6?SRC=Home) and [PlayReady Client SDK for Windows Store apps](http://visualstudiogallery.msdn.microsoft.com/e02ccac7-f3eb-4b53-b11a-c657d5631483). Remember to check out our [sample app](http://playerframework.codeplex.com/downloads/get/527085) to get started with APIs quickly. 

[Player Framework for Silverlight and Windows Phone](http://smf.codeplex.com/releases/view/88970)
Player Framework for Silverlight and Windows Phone enable you to build rich client experiences that take full advantage of both on-demand and live Smooth Streaming capabilities on computer desktops and on Windows Phone mobile devices. This framework is based on [Smooth Streaming Client SDK 2.0 RTW](http://www.microsoft.com/en-us/download/details.aspx?id=29940).  We also developed [health monitor app](http://smf.cloudapp.net/healthmonitor) based on this framework to help you diagnostic your application. 

[Windows Azure Media Services iOS Media Player Framework](https://github.com/WindowsAzure/azure-media-player-framework)
This framework enables developers to build native video application on iOS platform, which could consume secure Http Live Streaming content from Windows Azure Media Services. Mainly, this framework made easy for developers to integrate client-side advertisements. Please start with our [sample app](https://github.com/WindowsAzure/azure-media-player-framework/wiki/How-to-get-started-with-Github) and [wiki page](https://github.com/WindowsAzure/azure-media-player-framework/wiki/How-to-use-Azure-media-player-framework) to get started quickly.

**Comment by deneha** [comment]
@davidwrede Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
