### ISSUE TITLE
[Media Services] Download page Services and Client SDKs links change 

### ISSUE THREAD

**Issue by mingfeiy** [Azure/azure-content#997]
Referring to http://www.windowsazure.com/en-us/downloads/ under Media tab. I suggest the following change:
1. Rename the title as Media Services SDKs and Player frameworks 
2. Remove the Reference on the right side
3. Having the following six links under the title: 
- Media Services .NET SDK 
(link: http://nuget.org/packages/windowsazure.mediaservices)
- Media Services JAVA SDK
(link: https://github.com/windowsazure/azure-sdk-for-java/) 
- Player Framework for Windows 8
(http://playerframework.codeplex.com/releases/view/97333)
- Player Framework for iOS
(https://github.com/WindowsAzure/azure-media-player-framework)
- Player Framework for Silverlight and Windows Phone (If this title is too long, we could remove "And Windows Phone"
(link:http://smf.codeplex.com/releases/view/88970) 
- Smooth Streaming plugin for OSMF
(link: http://www.microsoft.com/en-us/download/details.aspx?id=36057)

This issue is linked with issue https://github.com/WindowsAzure/azure-content/issues/977. If this works, we could consider remove another download page mentioned in the linked issue 977.

**Comment by deneha** [comment]
@mingfeiy Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
