### ISSUE TITLE
[Media Services] Adding icons/images for Dev Center page 

### ISSUE THREAD

**Issue by mingfeiy** [Azure/azure-content#998]
There are no columes icon and banner icon for media services dev center page. http://www.windowsazure.com/en-us/develop/media-services/ 

We have the most important media conference coming from April 6-11 and we expect high traffic with dev center and hope this could be fixed.

**Comment by deneha** [comment]
@mingfeiy Thank you for raising this issue.  We're closing old issues.  If you feel this issue should remain open, please comment to let us know that the issue should be reopened.
